import {
  BankingNode,
  Transaction,
  Customer,
  Agent,
  Merchant,
  BDCOperator,
  LedgerEntry,
  ReconciliationException,
  SettlementBatch,
  RiskAlert,
  MakerCheckerRequest,
  AuditEvent,
  SystemHealthMetrics,
  CountryCode,
} from "@/types/admin";

// ==========================================
// 1. BANKING NODES DATA & TELEMETRY
// ==========================================
export const BANKING_NODES: BankingNode[] = [
  {
    id: "providus_ng",
    name: "Providus Bank Core Gateway",
    institution: "Providus Bank Plc (Nigeria)",
    country: "Nigeria",
    countryCode: "NG",
    currency: "NGN",
    health: "ONLINE",
    apiBaseUrl: "https://api.providusbank.com/v2/nip-gateway",
    latencyMs: 142,
    uptime24h: 99.98,
    successRate: 99.4,
    volume24h: 842150000,
    lastSuccessfulRequest: new Date(Date.now() - 1000 * 12).toISOString(),
    authStatus: "AUTHENTICATED",
    webhookStatus: "ACTIVE",
    settlementStatus: "SETTLED_T0",
    reconciliationStatus: "MATCHED",
    supportedServices: [
      "Dynamic Virtual Accounts (NUBAN)",
      "NIBSS Instant Payment (NIP) Outward",
      "Direct Debit Mandates",
      "Real-Time Webhook Receipts",
      "Agency Float Sweeping",
    ],
    isFailoverActive: false,
  },
  {
    id: "koris_ne",
    name: "Coris Bank Sahel Gateway",
    institution: "Coris Bank SA (Niger Republic)",
    country: "Niger Republic",
    countryCode: "NE",
    currency: "XOF",
    health: "ONLINE",
    apiBaseUrl: "https://api.korisbank.ne/core/v1/settlement",
    latencyMs: 188,
    uptime24h: 99.92,
    successRate: 98.9,
    volume24h: 418300000,
    lastSuccessfulRequest: new Date(Date.now() - 1000 * 25).toISOString(),
    authStatus: "AUTHENTICATED",
    webhookStatus: "ACTIVE",
    settlementStatus: "SETTLED_T0",
    reconciliationStatus: "MATCHED",
    supportedServices: [
      "WAEMU Interbank Clearing (GIM-UEMOA)",
      "Bilateral Cross-Border Settlement (NGN ⇄ XOF)",
      "Maradi & Niamey Commercial Agency Points",
      "Multi-Currency BDC Treasury Desks",
      "BCEAO Regulatory Export Logging",
    ],
    isFailoverActive: false,
  },
  {
    id: "korie_core",
    name: "KoriePay Unified Routing Core",
    institution: "KoriePay Financial Engine (Multi-Market)",
    country: "Global",
    countryCode: "GLOBAL",
    currency: "NGN",
    health: "ONLINE",
    apiBaseUrl: "https://api.koriepay.com/v1/engine",
    latencyMs: 38,
    uptime24h: 99.99,
    successRate: 99.8,
    volume24h: 1260450000,
    lastSuccessfulRequest: new Date().toISOString(),
    authStatus: "AUTHENTICATED",
    webhookStatus: "ACTIVE",
    settlementStatus: "SETTLED_T0",
    reconciliationStatus: "MATCHED",
    supportedServices: [
      "Double-Entry Cryptographic Ledger",
      "Real-Time Anomaly Telemetry",
      "FX Corridor Rate Engine",
      "Idempotency & Maker-Checker Queue",
      "REST & Webhook Dispatcher",
    ],
    isFailoverActive: false,
  },
];

// ==========================================
// 2. TRANSACTIONS REPOSITORY
// ==========================================
export const TRANSACTIONS: Transaction[] = [
  {
    id: "tx-kp-99812",
    reference: "KP-2026-XFER-99812",
    providerReference: "PRV-NIP-88419201",
    correlationId: "cor-ng-ne-00129",
    country: "Nigeria",
    countryCode: "NG",
    type: "TRANSFER_CROSS_BORDER",
    channel: "REST_API",
    amount: 1500000,
    fee: 3500,
    netAmount: 1496500,
    currency: "NGN",
    sourceCurrency: "NGN",
    destinationCurrency: "XOF",
    exchangeRate: 0.408,
    sourceAmount: 1500000,
    destinationAmount: 612000,
    status: "SUCCESSFUL",
    sender: {
      id: "cust-001",
      name: "Ibrahim Dawanau Agro Ltd",
      accountNumber: "0123984123",
      bankName: "Providus Bank Nigeria",
      walletId: "wlt-dawanau-01",
    },
    recipient: {
      id: "cust-092",
      name: "Maradi Grain Traders SARL",
      accountNumber: "NE020010012345678901",
      bankName: "Coris Bank Niger Republic",
      walletId: "wlt-maradi-88",
    },
    provider: {
      nodeId: "providus_ng",
      name: "Providus Bank Gateway",
      responseCode: "00",
      responseMessage: "Transaction Approved & Routed to Coris Bank Node",
      latencyMs: 210,
    },
    timeline: [
      { step: "Transaction Initiated via REST API", status: "COMPLETED", timestamp: "2026-09-03T01:10:00Z" },
      { step: "Risk & Velocity Verification Passed (Score 12)", status: "COMPLETED", timestamp: "2026-09-03T01:10:01Z" },
      { step: "Providus Bank Nigeria Core Inward Debit", status: "COMPLETED", timestamp: "2026-09-03T01:10:01Z" },
      { step: "Bilateral Corridor Conversion (NGN ⇄ XOF)", status: "COMPLETED", timestamp: "2026-09-03T01:10:02Z" },
      { step: "Coris Bank Niger Republic Inward Credit", status: "COMPLETED", timestamp: "2026-09-03T01:10:02Z" },
      { step: "Double-Entry Ledger Finalized", status: "COMPLETED", timestamp: "2026-09-03T01:10:03Z" },
    ],
    createdAt: "2026-09-03T01:10:00Z",
    completedAt: "2026-09-03T01:10:03Z",
    ipAddress: "197.210.84.12",
    deviceSignature: "SRV-NG-LGS-PROD-01",
    riskScore: 12,
    riskLevel: "LOW",
    isFlaggedForAML: false,
  },
  {
    id: "tx-kp-99813",
    reference: "KP-2026-POS-99813",
    providerReference: "KORIS-POS-109283",
    correlationId: "cor-ne-pos-4491",
    country: "Niger Republic",
    countryCode: "NE",
    type: "AGENCY_CASH_OUT",
    channel: "POS_TERMINAL",
    amount: 75000,
    fee: 450,
    netAmount: 74550,
    currency: "XOF",
    status: "SUCCESSFUL",
    sender: {
      id: "cust-044",
      name: "Mamadou Oumarou",
      accountNumber: "NE020088192301",
      bankName: "Coris Bank Niger Republic",
      walletId: "wlt-mamadou-19",
    },
    recipient: {
      id: "agent-012",
      name: "Niamey Grand Market Agency Point",
      accountNumber: "NE020099481230",
      bankName: "Coris Bank Niger Republic",
      walletId: "wlt-agent-niamey-02",
    },
    provider: {
      nodeId: "koris_ne",
      name: "Coris Bank Sahel Gateway",
      responseCode: "00",
      responseMessage: "Cash Out Authorized via Terminal Biometric",
      latencyMs: 165,
    },
    timeline: [
      { step: "Agent Smart POS Card Dip & Biometric Auth", status: "COMPLETED", timestamp: "2026-09-03T01:12:10Z" },
      { step: "Coris Bank Node Account Authorization", status: "COMPLETED", timestamp: "2026-09-03T01:12:11Z" },
      { step: "Agent Float Balance Credited Instantly", status: "COMPLETED", timestamp: "2026-09-03T01:12:11Z" },
      { step: "Terminal Receipt Dispatched & Printed", status: "COMPLETED", timestamp: "2026-09-03T01:12:12Z" },
    ],
    createdAt: "2026-09-03T01:12:10Z",
    completedAt: "2026-09-03T01:12:12Z",
    ipAddress: "41.138.64.91",
    deviceSignature: "POS-TER-NER-NIA-0041",
    riskScore: 8,
    riskLevel: "LOW",
    isFlaggedForAML: false,
  },
  {
    id: "tx-kp-99814",
    reference: "KP-2026-BDC-99814",
    providerReference: "PRV-FX-774812",
    correlationId: "cor-fx-kano-99",
    country: "Nigeria",
    countryCode: "NG",
    type: "BDC_FX_SWAP",
    channel: "BDC_PORTAL",
    amount: 12500000,
    fee: 15000,
    netAmount: 12485000,
    currency: "NGN",
    sourceCurrency: "NGN",
    destinationCurrency: "USD",
    exchangeRate: 1540.5,
    sourceAmount: 12500000,
    destinationAmount: 8114.24,
    status: "PROCESSING",
    sender: {
      id: "bdc-002",
      name: "Sahel Express BDC Consortium",
      accountNumber: "0991823102",
      bankName: "Providus Bank Nigeria",
      walletId: "wlt-sahel-bdc",
    },
    recipient: {
      id: "bdc-002-usd",
      name: "Sahel Express Foreign Treasury",
      accountNumber: "USD-DOM-991203",
      bankName: "Providus Bank Nigeria",
      walletId: "wlt-sahel-usd",
    },
    provider: {
      nodeId: "providus_ng",
      name: "Providus Bank Gateway",
      responseCode: "09",
      responseMessage: "High-Value FX Dual-Control Verification in Progress",
      latencyMs: 340,
    },
    timeline: [
      { step: "BDC Portal High-Value Order Submitted", status: "COMPLETED", timestamp: "2026-09-03T01:14:00Z" },
      { step: "Maker-Checker Requirement Triggered (>₦10M)", status: "COMPLETED", timestamp: "2026-09-03T01:14:01Z" },
      { step: "Awaiting Super Admin Treasury Approval", status: "PENDING", timestamp: "2026-09-03T01:14:02Z" },
    ],
    createdAt: "2026-09-03T01:14:00Z",
    riskScore: 68,
    riskLevel: "HIGH",
    isFlaggedForAML: true,
  },
  {
    id: "tx-kp-99815",
    reference: "KP-2026-QR-99815",
    providerReference: "KORIS-QR-4412",
    correlationId: "cor-qr-maradi-10",
    country: "Niger Republic",
    countryCode: "NE",
    type: "MERCHANT_QR_PAYMENT",
    channel: "MOBILE_APP",
    amount: 18500,
    fee: 150,
    netAmount: 18350,
    currency: "XOF",
    status: "SUCCESSFUL",
    sender: {
      id: "cust-078",
      name: "Zainab Moussa",
      accountNumber: "NE0200771829",
      bankName: "Coris Bank Niger Republic",
      walletId: "wlt-zainab-01",
    },
    recipient: {
      id: "mch-008",
      name: "Maradi Superette Central",
      accountNumber: "NE0200881923",
      bankName: "Coris Bank Niger Republic",
      walletId: "wlt-mch-maradi-01",
    },
    provider: {
      nodeId: "koris_ne",
      name: "Coris Bank Gateway",
      responseCode: "00",
      responseMessage: "Merchant Dynamic Standee QR Settled",
      latencyMs: 98,
    },
    timeline: [
      { step: "Dynamic QR Code Scanned in Store", status: "COMPLETED", timestamp: "2026-09-03T01:15:30Z" },
      { step: "Customer FaceID Authorized", status: "COMPLETED", timestamp: "2026-09-03T01:15:31Z" },
      { step: "Merchant Wallet Credited Instantly", status: "COMPLETED", timestamp: "2026-09-03T01:15:31Z" },
    ],
    createdAt: "2026-09-03T01:15:30Z",
    completedAt: "2026-09-03T01:15:31Z",
    riskScore: 5,
    riskLevel: "LOW",
    isFlaggedForAML: false,
  },
  {
    id: "tx-kp-99816",
    reference: "KP-2026-NIP-99816",
    providerReference: "PRV-NIP-994812",
    correlationId: "cor-nip-lagos-88",
    country: "Nigeria",
    countryCode: "NG",
    type: "TRANSFER_NIP",
    channel: "MOBILE_APP",
    amount: 450000,
    fee: 50,
    netAmount: 449950,
    currency: "NGN",
    status: "FAILED",
    sender: {
      id: "cust-019",
      name: "Chukwudi Okafor",
      accountNumber: "0219841203",
      bankName: "Providus Bank Nigeria",
      walletId: "wlt-chukwudi-01",
    },
    recipient: {
      id: "ext-cust-99",
      name: "Access Bank External Account",
      accountNumber: "0029182391",
      bankName: "Access Bank Nigeria",
    },
    provider: {
      nodeId: "providus_ng",
      name: "Providus Bank Gateway",
      responseCode: "91",
      responseMessage: "Destination Institution Switch Timeout (NIBSS 91)",
      latencyMs: 3820,
    },
    timeline: [
      { step: "App Transfer Initiated", status: "COMPLETED", timestamp: "2026-09-03T01:16:00Z" },
      { step: "Providus Outward NIP Dispatched", status: "COMPLETED", timestamp: "2026-09-03T01:16:01Z" },
      { step: "NIBSS Destination Switch Timeout", status: "FAILED", timestamp: "2026-09-03T01:16:05Z", detail: "Destination bank node unresponsive" },
      { step: "Customer Wallet Auto-Refunded", status: "COMPLETED", timestamp: "2026-09-03T01:16:05Z" },
    ],
    createdAt: "2026-09-03T01:16:00Z",
    completedAt: "2026-09-03T01:16:05Z",
    riskScore: 22,
    riskLevel: "LOW",
    isFlaggedForAML: false,
  },
];

// ==========================================
// 3. RECONCILIATION EXCEPTIONS QUEUE
// ==========================================
export const RECONCILIATION_EXCEPTIONS: ReconciliationException[] = [
  {
    id: "rec-exp-001",
    transactionId: "tx-kp-99780",
    providerReference: "PRV-NIP-998812",
    nodeId: "providus_ng",
    countryCode: "NG",
    expectedAmount: 250000,
    actualAmount: 250000,
    discrepancy: 0,
    currency: "NGN",
    type: "TIMING_DIFFERENCE",
    severity: "LOW",
    status: "INVESTIGATING",
    assignedTo: "Finance Operations Desk (Lagos)",
    notes: "Provider settlement cut-off timestamp 23:59 vs Internal Ledger 00:01",
    createdAt: "2026-09-02T23:59:12Z",
    updatedAt: "2026-09-03T01:00:00Z",
  },
  {
    id: "rec-exp-002",
    transactionId: "tx-kp-99712",
    providerReference: "KORIS-SETTL-00412",
    nodeId: "koris_ne",
    countryCode: "NE",
    expectedAmount: 850000,
    actualAmount: 848500,
    discrepancy: -1500,
    currency: "XOF",
    type: "MISMATCH",
    severity: "HIGH",
    status: "OPEN",
    assignedTo: "Niamey Treasury & Clearing Lead",
    notes: "Interbank stamp duty fee deduction not reflected in initial webhook payload",
    createdAt: "2026-09-02T18:30:00Z",
    updatedAt: "2026-09-03T00:45:00Z",
  },
];

// ==========================================
// 4. MAKER-CHECKER DUAL CONTROL QUEUE
// ==========================================
export const MAKER_CHECKER_REQUESTS: MakerCheckerRequest[] = [
  {
    id: "mc-req-101",
    actionType: "WALLET_FREEZE",
    resourceType: "AGENT_WALLET",
    resourceId: "wlt-agent-kano-99",
    resourceName: "Alhaji Bello Retail Outpost (Kano)",
    countryCode: "NG",
    requestedBy: "risk.officer@koriepay.com",
    requestedAt: "2026-09-03T00:50:00Z",
    reason: "Suspicious consecutive 15x cash-out attempts from mismatched device fingerprint",
    payload: {
      walletId: "wlt-agent-kano-99",
      currentBalance: 4820000,
      currency: "NGN",
      suspiciousIp: "105.112.98.11",
    },
    status: "PENDING",
  },
  {
    id: "mc-req-102",
    actionType: "SETTLEMENT_OVERRIDE",
    resourceType: "MERCHANT_SETTLEMENT",
    resourceId: "mch-batch-8841",
    resourceName: "Niamey Wholesale Rice Importers SARL",
    countryCode: "NE",
    requestedBy: "treasury.lead@koriepay.com",
    requestedAt: "2026-09-03T01:05:00Z",
    reason: "Urgent same-day cross-border batch release following verified physical customs clearance",
    payload: {
      batchId: "mch-batch-8841",
      grossAmount: 45000000,
      currency: "XOF",
      destinationNode: "koris_ne",
    },
    status: "PENDING",
  },
];

// ==========================================
// 5. IMMUTABLE FINANCIAL LEDGER
// ==========================================
export const LEDGER_ENTRIES: LedgerEntry[] = [
  {
    id: "led-00109",
    transactionId: "tx-kp-99812",
    reference: "KP-2026-XFER-99812",
    entryType: "DEBIT",
    accountType: "CUSTOMER_WALLET",
    accountIdentifier: "wlt-dawanau-01",
    currency: "NGN",
    amount: 1500000,
    balanceBefore: 8420000,
    balanceAfter: 6920000,
    actor: "SYSTEM_ROUTER",
    timestamp: "2026-09-03T01:10:01Z",
  },
  {
    id: "led-00110",
    transactionId: "tx-kp-99812",
    reference: "KP-2026-XFER-99812",
    entryType: "CREDIT",
    accountType: "BANK_CLEARING",
    accountIdentifier: "CLR-PROVIDUS-NGN-01",
    currency: "NGN",
    amount: 1496500,
    balanceBefore: 420000000,
    balanceAfter: 421496500,
    actor: "PROVIDUS_CONNECTOR",
    timestamp: "2026-09-03T01:10:02Z",
  },
  {
    id: "led-00111",
    transactionId: "tx-kp-99812",
    reference: "KP-2026-XFER-99812",
    entryType: "CREDIT",
    accountType: "FEE_REVENUE",
    accountIdentifier: "REV-KORIEPAY-NGN-01",
    currency: "NGN",
    amount: 3500,
    balanceBefore: 14280000,
    balanceAfter: 14283500,
    actor: "FEE_ENGINE",
    timestamp: "2026-09-03T01:10:02Z",
  },
  {
    id: "led-00112",
    transactionId: "tx-kp-99812",
    reference: "KP-2026-XFER-99812",
    entryType: "CREDIT",
    accountType: "CUSTOMER_WALLET",
    accountIdentifier: "wlt-maradi-88",
    currency: "XOF",
    amount: 612000,
    balanceBefore: 1200000,
    balanceAfter: 1812000,
    actor: "KORIS_CONNECTOR",
    timestamp: "2026-09-03T01:10:03Z",
  },
];

// ==========================================
// 6. CUSTOMERS, AGENTS & MERCHANTS DATA
// ==========================================
export const CUSTOMERS: Customer[] = [
  {
    id: "cust-001",
    fullName: "Ibrahim Dawanau Agro Ltd",
    email: "finance@dawanau-agro.com",
    phone: "+234 803 123 4567",
    country: "Nigeria",
    countryCode: "NG",
    kycTier: "TIER_3",
    kycStatus: "APPROVED",
    nationalIdNumber: "NIN 234****981",
    bvn: "BVN 223****123",
    walletId: "wlt-dawanau-01",
    availableBalance: 6920000,
    ledgerBalance: 6920000,
    currency: "NGN",
    totalTransactions: 482,
    totalVolume: 84200000,
    riskStatus: "NORMAL",
    status: "ACTIVE",
    createdAt: "2025-11-10T09:00:00Z",
    lastLoginAt: "2026-09-03T01:05:00Z",
    devicesCount: 3,
  },
  {
    id: "cust-044",
    fullName: "Mamadou Oumarou",
    email: "mamadou.oumarou@saheltrade.ne",
    phone: "+227 90 12 34 56",
    country: "Niger Republic",
    countryCode: "NE",
    kycTier: "TIER_2",
    kycStatus: "APPROVED",
    nationalIdNumber: "CNI NE-04-19283",
    walletId: "wlt-mamadou-19",
    availableBalance: 1450000,
    ledgerBalance: 1450000,
    currency: "XOF",
    totalTransactions: 129,
    totalVolume: 18450000,
    riskStatus: "NORMAL",
    status: "ACTIVE",
    createdAt: "2026-01-15T14:30:00Z",
    lastLoginAt: "2026-09-03T01:12:00Z",
    devicesCount: 2,
  },
];

export const AGENTS: Agent[] = [
  {
    id: "agent-001",
    businessName: "Kano Central Agency Kiosk",
    agentName: "Alhaji Garba Sani",
    phone: "+234 802 998 1234",
    email: "garba.kano@korieagent.com",
    country: "Nigeria",
    countryCode: "NG",
    stateOrRegion: "Kano State",
    lgaOrCity: "Fagge LGA",
    terminalCount: 2,
    activeTerminalId: "POS-NG-KAN-0042",
    walletId: "wlt-agent-kano-01",
    floatBalance: 3200000,
    commissionEarned24h: 42500,
    commissionTotal: 1840000,
    currency: "NGN",
    cashInVolume30d: 48500000,
    cashOutVolume30d: 52100000,
    transactionCount30d: 4820,
    successRate: 99.6,
    status: "ACTIVE",
    liquidityStatus: "HEALTHY",
    riskScore: 6,
    createdAt: "2025-08-20T10:00:00Z",
  },
  {
    id: "agent-012",
    businessName: "Niamey Grand Market Agency Point",
    agentName: "Abdoulaye Hamidou",
    phone: "+227 96 44 11 22",
    email: "abdoulaye@niamey-agent.ne",
    country: "Niger Republic",
    countryCode: "NE",
    stateOrRegion: "Niamey Region",
    lgaOrCity: "Niamey Commune 1",
    terminalCount: 1,
    activeTerminalId: "POS-TER-NER-NIA-0041",
    walletId: "wlt-agent-niamey-02",
    floatBalance: 2450000,
    commissionEarned24h: 28400,
    commissionTotal: 980000,
    currency: "XOF",
    cashInVolume30d: 28400000,
    cashOutVolume30d: 31000000,
    transactionCount30d: 2940,
    successRate: 99.1,
    status: "ACTIVE",
    liquidityStatus: "HEALTHY",
    riskScore: 9,
    createdAt: "2026-02-01T08:00:00Z",
  },
];

export const MERCHANTS: Merchant[] = [
  {
    id: "mch-001",
    businessName: "Sahara Wholesale Supermarket",
    ownerName: "Tunde Bakare",
    businessType: "Retail & FMCG",
    country: "Nigeria",
    countryCode: "NG",
    city: "Lagos",
    settlementBank: "Providus Bank Nigeria",
    settlementAccountMasked: "0123****91",
    walletId: "wlt-mch-sahara-01",
    currency: "NGN",
    grossSales30d: 94200000,
    netSettlementPending: 2840000,
    successRate: 99.7,
    disputeCount: 1,
    activeQRCodes: 12,
    activePOSTerminals: 4,
    status: "ACTIVE",
    createdAt: "2025-09-12T11:00:00Z",
  },
  {
    id: "mch-008",
    businessName: "Maradi Superette Central",
    ownerName: "Ousseini Dan Kaka",
    businessType: "Grocery & Hardware",
    country: "Niger Republic",
    countryCode: "NE",
    city: "Maradi",
    settlementBank: "Coris Bank Niger Republic",
    settlementAccountMasked: "NE02****23",
    walletId: "wlt-mch-maradi-01",
    currency: "XOF",
    grossSales30d: 38400000,
    netSettlementPending: 1200000,
    successRate: 99.3,
    disputeCount: 0,
    activeQRCodes: 4,
    activePOSTerminals: 1,
    status: "ACTIVE",
    createdAt: "2026-02-18T09:30:00Z",
  },
];

export const BDC_OPERATORS: BDCOperator[] = [
  {
    id: "bdc-001",
    operatorName: "Kano Sahel Foreign Exchange BDC",
    licenseNumber: "CBN/BDC/KN/2024/091",
    country: "Nigeria",
    countryCode: "NG",
    primaryCorridor: "Kano ⇄ Maradi",
    treasuryNGN: 184000000,
    treasuryXOF: 78000000,
    treasuryUSD: 240000,
    dailyTradingVolume: 42000000,
    buyRateSpread: 0.406,
    sellRateSpread: 0.41,
    status: "ACTIVE",
    complianceScore: 98,
    createdAt: "2025-06-10T10:00:00Z",
  },
  {
    id: "bdc-002",
    operatorName: "Sahel Express BDC Consortium",
    licenseNumber: "BCEAO/CHANGE/NER/2025/012",
    country: "Niger Republic",
    countryCode: "NE",
    primaryCorridor: "Lagos ⇄ Niamey",
    treasuryNGN: 92000000,
    treasuryXOF: 145000000,
    treasuryUSD: 410000,
    dailyTradingVolume: 68000000,
    buyRateSpread: 2.44,
    sellRateSpread: 2.47,
    status: "ACTIVE",
    complianceScore: 95,
    createdAt: "2025-09-01T12:00:00Z",
  },
];

// ==========================================
// 7. EXECUTIVE INTELLIGENCE & METRICS AGGREGATOR
// ==========================================

