import {
  AggregatorOrganization,
  AggregatedAgent,
  AggregatedMerchant,
  AggregatedTerritory,
  AggregatorTransaction,
  AggregatorLiquidityPosition,
  AggregatorCommissionSummary,
  AggregatorSettlementRecord,
  AggregatorReconciliationRecord,
  AggregatorExceptionRecord,
  AggregatorRiskAlert,
  AggregatorComplianceRecord,
  AggregatorServiceHealth,
  AggregatorTeamMember,
  AggregatorTarget,
} from "@/types/aggregator";

// =========================================================================
// 1. AUTHENTICATED AGGREGATOR ORGANIZATION
// =========================================================================
export const CURRENT_AGGREGATOR: AggregatorOrganization = {
  id: "agg-sahel-001",
  name: "Sahel Agency & Merchant Distribution Syndicate Ltd",
  code: "AGG-SAHEL-001",
  rcNumber: "RC-1849201",
  country: "NG",
  currency: "NGN",
  tier: "TIER_1_SUPER_AGGREGATOR",
  status: "ACTIVE",
  territoriesCovered: ["Kano North & Urban", "Kaduna Metro", "Abuja FCT Central", "Lagos West", "Niamey Commercial"],
  headquarters: "Suite 402, Sahel Commerce Tower, Murtala Mohammed Way, Kano / Plot 88 Victoria Island, Lagos",
  contactEmail: "executive@sahel-syndicate.ng",
  contactPhone: "+234 64 881 920",
  walletBalance: 42850000,
  availableLiquidity: 36500000,
  escrowBalance: 6350000,
  pendingCommissions: 2840000,
  settledCommissionsThisMonth: 14920000,
  totalNetworkTPVToday: 68420000,
  totalNetworkTPVMonth: 1845000000,
  totalNetworkTransactionsToday: 3840,
  activeAgentsCount: 248,
  inactiveAgentsCount: 12,
  activeMerchantsCount: 84,
  inactiveMerchantsCount: 6,
  settlementBank: "Providus Bank Nigeria",
  settlementAccountMasked: "0182****29",
  providerNodeNG: "Providus Bank Nigeria (Connected)",
  providerNodeNE: "Koris Bank Niger Republic (Connected)",
  createdAt: "2023-01-10T08:00:00Z",
};

// =========================================================================
// 2. AGGREGATED AGENT NETWORK DIRECTORY
// =========================================================================
export const AGGREGATED_AGENTS: AggregatedAgent[] = [
  {
    id: "agt-001",
    agentCode: "AGT-KN-0104",
    fullName: "Alhaji Ibrahim Dan-Batta",
    businessName: "Dan-Batta Agro Agency & POS Point",
    phone: "+234 803 219 8812",
    email: "ibrahim@danbatta-agency.ng",
    country: "NG",
    state: "Kano State",
    lga: "Dawanau / Fagge",
    territoryId: "ter-kn-01",
    territoryName: "Kano North & Urban",
    branchName: "Dawanau Central Market Agency Node",
    status: "ACTIVE",
    kycTier: "TIER_3",
    kycStatus: "VERIFIED",
    walletBalance: 2450000,
    cashInDrawer: 1800000,
    totalLiquidity: 4250000,
    todayTransactionsCount: 142,
    todayVolume: 8450000,
    todayCommission: 42250,
    monthlyVolume: 128400000,
    successRate: 99.4,
    posTerminalCount: 3,
    lastActiveAt: "2 mins ago",
    riskStatus: "LOW",
    registeredAt: "2024-02-14",
  },
  {
    id: "agt-002",
    agentCode: "AGT-KD-0210",
    fullName: "Bello Mansur",
    businessName: "Mansur Express Agency & Cashpoint",
    phone: "+234 802 881 9904",
    country: "NG",
    state: "Kaduna State",
    lga: "Kaduna North / Central Market",
    territoryId: "ter-kd-02",
    territoryName: "Kaduna Metro",
    branchName: "Ahmadu Bello Way Hub",
    status: "ACTIVE",
    kycTier: "TIER_3",
    kycStatus: "VERIFIED",
    walletBalance: 1280000,
    cashInDrawer: 950000,
    totalLiquidity: 2230000,
    todayTransactionsCount: 88,
    todayVolume: 4120000,
    todayCommission: 20600,
    monthlyVolume: 64200000,
    successRate: 98.8,
    posTerminalCount: 2,
    lastActiveAt: "Just now",
    riskStatus: "LOW",
    registeredAt: "2024-04-10",
  },
  {
    id: "agt-003",
    agentCode: "AGT-ABJ-0301",
    fullName: "Chukwudi Nnamdi",
    businessName: "Capital Link Multi-Services",
    phone: "+234 809 112 3344",
    email: "chukwudi@capitallink.ng",
    country: "NG",
    state: "Abuja FCT",
    lga: "Municipal / Wuse Zone 4",
    territoryId: "ter-abj-03",
    territoryName: "Abuja FCT Central",
    branchName: "Wuse 4 FX & Agency Center",
    status: "ACTIVE",
    kycTier: "TIER_3",
    kycStatus: "VERIFIED",
    walletBalance: 3840000,
    cashInDrawer: 2400000,
    totalLiquidity: 6240000,
    todayTransactionsCount: 164,
    todayVolume: 12800000,
    todayCommission: 64000,
    monthlyVolume: 215000000,
    successRate: 99.8,
    posTerminalCount: 4,
    lastActiveAt: "5 mins ago",
    riskStatus: "LOW",
    registeredAt: "2023-11-20",
  },
  {
    id: "agt-004",
    agentCode: "AGT-KN-0149",
    fullName: "Amina Yusuf Garko",
    businessName: "Garko Women Micro-Finance & POS",
    phone: "+234 813 449 1029",
    country: "NG",
    state: "Kano State",
    lga: "Kano Municipal / Kurmi Market",
    territoryId: "ter-kn-01",
    territoryName: "Kano North & Urban",
    branchName: "Kurmi Heritage Node",
    status: "ACTIVE",
    kycTier: "TIER_2",
    kycStatus: "VERIFIED",
    walletBalance: 420000,
    cashInDrawer: 680000,
    totalLiquidity: 1100000,
    todayTransactionsCount: 52,
    todayVolume: 1850000,
    todayCommission: 9250,
    monthlyVolume: 32000000,
    successRate: 97.4,
    posTerminalCount: 1,
    lastActiveAt: "12 mins ago",
    riskStatus: "LOW",
    registeredAt: "2024-06-01",
  },
  {
    id: "agt-005",
    agentCode: "AGT-NIA-0501",
    fullName: "Mamadou Souleymane",
    businessName: "Sahel Express Guichet Unique Niamey",
    phone: "+227 90 22 44 66",
    email: "mamadou@sahel-guichet.ne",
    country: "NE",
    state: "Niamey Region",
    lga: "Commune 1 / Grand Marché",
    territoryId: "ter-nia-05",
    territoryName: "Niamey Commercial",
    branchName: "Niamey Grand Marché Hub",
    status: "ACTIVE",
    kycTier: "TIER_3",
    kycStatus: "VERIFIED",
    walletBalance: 4800000,
    cashInDrawer: 3100000,
    totalLiquidity: 7900000,
    todayTransactionsCount: 74,
    todayVolume: 6400000,
    todayCommission: 32000,
    monthlyVolume: 96000000,
    successRate: 99.1,
    posTerminalCount: 2,
    lastActiveAt: "1 min ago",
    riskStatus: "LOW",
    registeredAt: "2024-01-18",
  },
  {
    id: "agt-006",
    agentCode: "AGT-KN-0188",
    fullName: "Kabiru Lawan",
    businessName: "Kantin Kwari Float Point 4",
    phone: "+234 806 771 8820",
    country: "NG",
    state: "Kano State",
    lga: "Fagge / Kwari Market",
    territoryId: "ter-kn-01",
    territoryName: "Kano North & Urban",
    branchName: "Kwari Textile Terminal",
    status: "RESTRICTED",
    kycTier: "TIER_2",
    kycStatus: "ACTION_REQUIRED",
    walletBalance: 85000,
    cashInDrawer: 120000,
    totalLiquidity: 205000,
    todayTransactionsCount: 8,
    todayVolume: 190000,
    todayCommission: 950,
    monthlyVolume: 4200000,
    successRate: 84.2,
    posTerminalCount: 1,
    lastActiveAt: "3 hours ago",
    riskStatus: "FLAGGED",
    registeredAt: "2024-05-12",
  },
];

// =========================================================================
// 3. AGGREGATED MERCHANT NETWORK DIRECTORY
// =========================================================================
export const AGGREGATED_MERCHANTS: AggregatedMerchant[] = [
  {
    id: "mch-001",
    merchantCode: "MCH-DAW-0901",
    businessName: "Dawanau Wholesale Grain Consolidated Ltd",
    tradingName: "Dawanau Grain Stores",
    contactPerson: "Alhaji Lawal Dawanau",
    phone: "+234 803 991 2288",
    email: "procurement@dawanaugrain.ng",
    country: "NG",
    category: "Agro-Commodities & Wholesale Grains",
    territoryName: "Kano North & Urban",
    branchName: "Kano Main Depot",
    status: "ACTIVE",
    kybStatus: "VERIFIED",
    todayVolume: 24800000,
    todayTxCount: 46,
    monthVolume: 420000000,
    averageTicket: 539130,
    settlementBank: "Providus Bank Nigeria",
    settlementAccountMasked: "0199****12",
    disputeRate: 0.01,
    refundRate: 0.02,
    riskState: "NORMAL",
    lastActivityAt: "4 mins ago",
    registeredAt: "2023-08-10",
  },
  {
    id: "mch-002",
    merchantCode: "MCH-KWR-0820",
    businessName: "Arewa Textile & Fabric Merchants Consortium",
    tradingName: "Kantin Kwari Silk & Brocade",
    contactPerson: "Hajiya Mariam Sanusi",
    phone: "+234 802 771 9934",
    email: "finance@arewatextiles.ng",
    country: "NG",
    category: "Apparel, Fabrics & Wholesale Textiles",
    territoryName: "Kano North & Urban",
    branchName: "Kwari Commercial Center",
    status: "ACTIVE",
    kybStatus: "VERIFIED",
    todayVolume: 16400000,
    todayTxCount: 82,
    monthVolume: 285000000,
    averageTicket: 200000,
    settlementBank: "Providus Bank Nigeria",
    settlementAccountMasked: "0177****49",
    disputeRate: 0.03,
    refundRate: 0.05,
    riskState: "NORMAL",
    lastActivityAt: "10 mins ago",
    registeredAt: "2023-10-04",
  },
  {
    id: "mch-003",
    merchantCode: "MCH-NIA-0701",
    businessName: "Maradi-Niamey Cross-Border Transit SARL",
    tradingName: "Sahel Cross-Border Logistics & Trade",
    contactPerson: "Ousseini Abdoulaye",
    phone: "+227 96 11 33 55",
    email: "trade@saheltransit.ne",
    country: "NE",
    category: "Logistics, Cross-Border Freight & FMCG",
    territoryName: "Niamey Commercial",
    branchName: "Niamey Free Trade Depot",
    status: "ACTIVE",
    kybStatus: "VERIFIED",
    todayVolume: 12200000,
    todayTxCount: 29,
    monthVolume: 194000000,
    averageTicket: 420689,
    settlementBank: "Koris Bank Niger Republic",
    settlementAccountMasked: "NE48****88",
    disputeRate: 0.02,
    refundRate: 0.01,
    riskState: "NORMAL",
    lastActivityAt: "15 mins ago",
    registeredAt: "2024-01-20",
  },
];

// =========================================================================
// 4. TERRITORIES
// =========================================================================
export const AGGREGATED_TERRITORIES: AggregatedTerritory[] = [
  {
    id: "ter-kn-01",
    name: "Kano North & Urban",
    code: "TER-KN-01",
    country: "NG",
    stateOrRegion: "Kano State",
    lgaOrCommune: "Fagge, Dawanau, Nassarawa, Municipal",
    supervisorName: "Dr. Mukhtar Dan-Iya",
    supervisorPhone: "+234 803 111 2233",
    activeAgentsCount: 114,
    activeMerchantsCount: 42,
    todayTPV: 34500000,
    monthlyTPV: 890000000,
    aggregatorCommissionToday: 172500,
    liquidityHealth: "HEALTHY",
    riskLevel: "LOW",
  },
  {
    id: "ter-kd-02",
    name: "Kaduna Metro",
    code: "TER-KD-02",
    country: "NG",
    stateOrRegion: "Kaduna State",
    lgaOrCommune: "Kaduna North, Kaduna South, Chikun",
    supervisorName: "Habibu Garba",
    supervisorPhone: "+234 802 333 4455",
    activeAgentsCount: 56,
    activeMerchantsCount: 18,
    todayTPV: 14800000,
    monthlyTPV: 380000000,
    aggregatorCommissionToday: 74000,
    liquidityHealth: "HEALTHY",
    riskLevel: "LOW",
  },
  {
    id: "ter-abj-03",
    name: "Abuja FCT Central",
    code: "TER-ABJ-03",
    country: "NG",
    stateOrRegion: "Abuja FCT",
    lgaOrCommune: "Municipal, Garki, Wuse, Maitama",
    supervisorName: "Ngozi Eze",
    supervisorPhone: "+234 809 444 5566",
    activeAgentsCount: 48,
    activeMerchantsCount: 14,
    todayTPV: 12900000,
    monthlyTPV: 360000000,
    aggregatorCommissionToday: 64500,
    liquidityHealth: "HEALTHY",
    riskLevel: "LOW",
  },
  {
    id: "ter-nia-05",
    name: "Niamey Commercial",
    code: "TER-NIA-05",
    country: "NE",
    stateOrRegion: "Niamey Region",
    lgaOrCommune: "Commune 1, Commune 2, Zone Industrielle",
    supervisorName: "Seydou Kountché",
    supervisorPhone: "+227 90 88 77 66",
    activeAgentsCount: 30,
    activeMerchantsCount: 10,
    todayTPV: 6220000,
    monthlyTPV: 215000000,
    aggregatorCommissionToday: 31100,
    liquidityHealth: "HEALTHY",
    riskLevel: "LOW",
  },
];

// =========================================================================
// 5. AGGREGATOR LIVE TRANSACTION FEED
// =========================================================================
export const AGGREGATOR_TRANSACTIONS: AggregatorTransaction[] = [
  {
    id: "tx-agg-99201",
    reference: "KP-TX-2026-99201",
    correlationId: "CORR-9948102-SAHEL",
    providerReference: "PROV-NIP-99281048",
    entityType: "AGENT",
    agentId: "agt-001",
    agentName: "Dan-Batta Agro Agency & POS Point",
    customerName: "Alhaji Haruna Sani",
    customerPhone: "+234 803 910 2938",
    country: "NG",
    territoryName: "Kano North & Urban",
    type: "CASH_OUT",
    channel: "CARD_POS",
    amount: 150000,
    fee: 300,
    agentCommission: 150,
    aggregatorCommission: 75,
    netSettledToEntity: 149700,
    currency: "NGN",
    status: "SUCCESSFUL",
    providerNode: "Providus Bank / Interswitch",
    settlementStatus: "SCHEDULED",
    createdAt: "2026-09-03T11:58:20Z",
    timeline: [
      { stage: "CREATED", timestamp: "11:58:20", status: "COMPLETED", description: "Card inserted on PAX POS Terminal" },
      { stage: "INITIATED", timestamp: "11:58:21", status: "COMPLETED", description: "PIN authenticated via NIBSS Key" },
      { stage: "PROCESSING", timestamp: "11:58:22", status: "COMPLETED", description: "Switching via Interswitch Gateway" },
      { stage: "PROVIDER_DISPATCH", timestamp: "11:58:23", status: "COMPLETED", description: "Providus Bank debit successful" },
      { stage: "CONFIRMED", timestamp: "11:58:24", status: "COMPLETED", description: "Slip printed; Drawer cash dispensed" },
      { stage: "LEDGER_POSTED", timestamp: "11:58:24", status: "COMPLETED", description: "Double-entry split posted to ledger" },
      { stage: "SETTLED", timestamp: "23:59:00", status: "PENDING", description: "Pending nightly Providus NIP batch" },
    ],
  },
  {
    id: "tx-agg-99202",
    reference: "KP-TX-2026-99202",
    correlationId: "CORR-9948103-SAHEL",
    providerReference: "PROV-NIP-99281049",
    entityType: "MERCHANT",
    merchantId: "mch-001",
    merchantName: "Dawanau Wholesale Grain Consolidated Ltd",
    customerName: "Borno Food Security Trust",
    customerPhone: "+234 802 441 9028",
    country: "NG",
    territoryName: "Kano North & Urban",
    type: "PAYMENT",
    channel: "BANK_TRANSFER",
    amount: 4500000,
    fee: 4500,
    agentCommission: 0,
    aggregatorCommission: 2250,
    netSettledToEntity: 4495500,
    currency: "NGN",
    status: "SUCCESSFUL",
    providerNode: "Providus Dynamic NUBAN",
    settlementStatus: "SCHEDULED",
    createdAt: "2026-09-03T11:52:10Z",
    timeline: [
      { stage: "CREATED", timestamp: "11:50:00", status: "COMPLETED", description: "Providus Dynamic NUBAN generated" },
      { stage: "INITIATED", timestamp: "11:51:30", status: "COMPLETED", description: "Customer initiated NIP Bank Transfer" },
      { stage: "PROCESSING", timestamp: "11:52:00", status: "COMPLETED", description: "NIBSS credit message ingested" },
      { stage: "PROVIDER_DISPATCH", timestamp: "11:52:05", status: "COMPLETED", description: "Providus webhook signature verified" },
      { stage: "CONFIRMED", timestamp: "11:52:10", status: "COMPLETED", description: "Invoice marked as paid in full" },
      { stage: "LEDGER_POSTED", timestamp: "11:52:10", status: "COMPLETED", description: "Escrow credited; commission accrued" },
      { stage: "SETTLED", timestamp: "23:59:00", status: "PENDING", description: "Providus auto-sweep scheduled" },
    ],
  },
  {
    id: "tx-agg-99203",
    reference: "KP-TX-2026-99203",
    correlationId: "CORR-9948104-SAHEL",
    providerReference: "KORIS-BCEAO-771029",
    entityType: "MERCHANT",
    merchantId: "mch-003",
    merchantName: "Maradi-Niamey Cross-Border Transit SARL",
    customerName: "Sahel Agrum SARL Niamey",
    country: "NE",
    territoryName: "Niamey Commercial",
    type: "PAYMENT_LINK",
    channel: "PAYMENT_LINK",
    amount: 1200000,
    fee: 18000,
    agentCommission: 0,
    aggregatorCommission: 6000,
    netSettledToEntity: 1182000,
    currency: "NGN",
    status: "SUCCESSFUL",
    providerNode: "Koris Bank Niger Republic",
    settlementStatus: "SCHEDULED",
    createdAt: "2026-09-03T11:45:00Z",
    timeline: [
      { stage: "CREATED", timestamp: "11:40:00", status: "COMPLETED", description: "Checkout link generated" },
      { stage: "INITIATED", timestamp: "11:44:00", status: "COMPLETED", description: "Customer paid with BCEAO GIM-UEMOA Card" },
      { stage: "PROCESSING", timestamp: "11:44:40", status: "COMPLETED", description: "3D-Secure OTP verified" },
      { stage: "PROVIDER_DISPATCH", timestamp: "11:44:55", status: "COMPLETED", description: "Koris Bank authorization received" },
      { stage: "CONFIRMED", timestamp: "11:45:00", status: "COMPLETED", description: "Payment finalized" },
      { stage: "LEDGER_POSTED", timestamp: "11:45:00", status: "COMPLETED", description: "Ledger entries posted" },
      { stage: "SETTLED", timestamp: "23:59:00", status: "PENDING", description: "Batch settlement queued" },
    ],
  },
  {
    id: "tx-agg-99204",
    reference: "KP-TX-2026-99204",
    correlationId: "CORR-9948105-SAHEL",
    providerReference: "PROV-NIP-99281052",
    entityType: "AGENT",
    agentId: "agt-006",
    agentName: "Kantin Kwari Float Point 4",
    customerName: "Suleiman Garba",
    country: "NG",
    territoryName: "Kano North & Urban",
    type: "TRANSFER",
    channel: "BANK_TRANSFER",
    amount: 85000,
    fee: 150,
    agentCommission: 0,
    aggregatorCommission: 0,
    netSettledToEntity: 0,
    currency: "NGN",
    status: "FAILED",
    providerNode: "Providus Bank / NIBSS",
    failureReason: "Agent wallet float balance insufficient for transfer debit.",
    settlementStatus: "EXCLUDED",
    createdAt: "2026-09-03T11:30:15Z",
    timeline: [
      { stage: "CREATED", timestamp: "11:30:10", status: "COMPLETED", description: "Transfer request initiated" },
      { stage: "INITIATED", timestamp: "11:30:12", status: "COMPLETED", description: "Pre-validation checks run" },
      { stage: "PROCESSING", timestamp: "11:30:15", status: "FAILED", description: "Debit rejected: Insufficient Agent Float" },
    ],
  },
];

// =========================================================================
// 6. LIQUIDITY POSITION
// =========================================================================
export const AGGREGATOR_LIQUIDITY: AggregatorLiquidityPosition = {
  aggregatorMainWallet: 42850000,
  aggregatorReserveWallet: 15000000,
  totalAgentFloatLiquidity: 32450000,
  totalMerchantSettlementFloat: 64200000,
  estimatedCashInNetworkDrawer: 28900000,
  networkLiquidityHealth: "HEALTHY",
  agentsUnderMinimumThresholdCount: 4,
  agentsRequiringFloatCount: 2,
};

// =========================================================================
// 7. COMMISSIONS SUMMARY
// =========================================================================
export const AGGREGATOR_COMMISSIONS: AggregatorCommissionSummary = {
  todayEarned: 342150,
  thisWeekEarned: 2418000,
  thisMonthEarned: 14920000,
  pendingClearance: 2840000,
  approvedForPayout: 12080000,
  settledToBank: 142500000,
  lifetimeTotal: 184920000,
  byService: [
    { serviceName: "Agency Cash-Out / In", volume: 28400000, commission: 142000, percentage: 41.5 },
    { serviceName: "Merchant Dynamic NUBAN Transfers", volume: 24800000, commission: 124000, percentage: 36.2 },
    { serviceName: "Card POS Terminals", volume: 11200000, commission: 56000, percentage: 16.4 },
    { serviceName: "VAS, Airtime & Bill Payments", volume: 4020000, commission: 20150, percentage: 5.9 },
  ],
};

// =========================================================================
// 8. SETTLEMENT RECORDS
// =========================================================================
export const AGGREGATOR_SETTLEMENTS: AggregatorSettlementRecord[] = [
  {
    id: "stl-agg-001",
    batchReference: "PRV-SETTL-AGG-2026-0902",
    nibssSessionId: "99281029381029384",
    providerRef: "PROV-NIP-STL-8812",
    settlementDate: "2026-09-02",
    grossNetworkVolume: 74200000,
    totalInterchangeFees: 371000,
    refundsAdjusted: 0,
    netAggregatorCommissionSettled: 371000,
    currency: "NGN",
    destinationBank: "Providus Bank Nigeria",
    destinationAccountMasked: "0182****29",
    status: "COMPLETED",
    includedTransactionsCount: 4120,
    settledAt: "2026-09-02T23:59:00Z",
  },
  {
    id: "stl-agg-002",
    batchReference: "PRV-SETTL-AGG-2026-0901",
    nibssSessionId: "99281029381029370",
    providerRef: "PROV-NIP-STL-8801",
    settlementDate: "2026-09-01",
    grossNetworkVolume: 68900000,
    totalInterchangeFees: 344500,
    refundsAdjusted: 0,
    netAggregatorCommissionSettled: 344500,
    currency: "NGN",
    destinationBank: "Providus Bank Nigeria",
    destinationAccountMasked: "0182****29",
    status: "COMPLETED",
    includedTransactionsCount: 3890,
    settledAt: "2026-09-01T23:59:00Z",
  },
];

// =========================================================================
// 9. RECONCILIATION MATCHING
// =========================================================================
export const AGGREGATOR_RECONCILIATION: AggregatorReconciliationRecord[] = [
  {
    id: "rec-01",
    date: "2026-09-02",
    channelOrEntity: "Agency Cash-In / Cash-Out Network",
    providerNode: "Providus Bank NG / NIBSS",
    internalLedgerTotal: 34500000,
    providerGatewayTotal: 34500000,
    bankSettledTotal: 34500000,
    varianceAmount: 0,
    variancePercentage: 0,
    status: "MATCHED",
    discrepancyCount: 0,
  },
  {
    id: "rec-02",
    date: "2026-09-02",
    channelOrEntity: "Merchant Dynamic Virtual Transfers",
    providerNode: "Providus Bank Dynamic NUBAN",
    internalLedgerTotal: 27500000,
    providerGatewayTotal: 27500000,
    bankSettledTotal: 27500000,
    varianceAmount: 0,
    variancePercentage: 0,
    status: "MATCHED",
    discrepancyCount: 0,
  },
  {
    id: "rec-03",
    date: "2026-09-02",
    channelOrEntity: "Niamey BCEAO Regional Route",
    providerNode: "Koris Bank Niger Republic",
    internalLedgerTotal: 12200000,
    providerGatewayTotal: 12200000,
    bankSettledTotal: 12200000,
    varianceAmount: 0,
    variancePercentage: 0,
    status: "MATCHED",
    discrepancyCount: 0,
  },
];

// =========================================================================
// 10. EXCEPTIONS & RISK
// =========================================================================
export const AGGREGATOR_EXCEPTIONS: AggregatorExceptionRecord[] = [
  {
    id: "exc-001",
    reference: "EXC-2026-0041",
    category: "WALLET",
    severity: "HIGH",
    affectedEntity: "AGT-KN-0188 (Kantin Kwari Float Point 4)",
    detectedAt: "2026-09-03T11:30:15Z",
    currentState: "ACTION_REQUIRED",
    owner: "Operations Desk / Field Lead",
    description: "Agent float fell below minimum required threshold (₦85,000 available vs ₦250,000 min). 3 transfer requests rejected.",
    recommendedAction: "Execute float top-up from Aggregator Main Wallet or notify Field Officer for cash deposit.",
  },
  {
    id: "exc-002",
    reference: "EXC-2026-0042",
    category: "COMPLIANCE",
    severity: "MEDIUM",
    affectedEntity: "AGT-KN-0149 (Garko Women Micro-Finance)",
    detectedAt: "2026-09-02T16:00:00Z",
    currentState: "INVESTIGATING",
    owner: "Compliance Officer",
    description: "NIN document verification re-validation required by CBN regulatory periodic KYC refresh.",
    recommendedAction: "Request updated utility bill and NIN consent verification slip.",
  },
];

export const AGGREGATOR_RISK_ALERTS: AggregatorRiskAlert[] = [
  {
    id: "risk-001",
    alertType: "VELOCITY_ANOMALY",
    severity: "HIGH",
    entityType: "AGENT",
    entityName: "Kantin Kwari Float Point 4",
    entityId: "agt-006",
    details: "Unusual concentration of 4 rapid card cash-out attempts with consecutive failure responses within 6 minutes.",
    recommendedAction: "Temporarily restrict POS card terminal processing pending terminal security verification.",
    status: "OPEN",
    detectedAt: "2026-09-03T11:28:00Z",
  },
];

export const AGGREGATOR_COMPLIANCE_QUEUE: AggregatorComplianceRecord[] = [
  {
    id: "cmp-01",
    entityType: "AGENT",
    entityId: "agt-004",
    entityName: "Amina Yusuf Garko",
    territoryName: "Kano North & Urban",
    documentType: "NIN_BVN_VALIDATION",
    submittedAt: "2026-09-02T14:30:00Z",
    status: "PENDING_REVIEW",
  },
  {
    id: "cmp-02",
    entityType: "MERCHANT",
    entityId: "mch-002",
    entityName: "Arewa Textile Consortium",
    territoryName: "Kano North & Urban",
    documentType: "CAC_CERTIFICATE",
    submittedAt: "2026-09-01T10:00:00Z",
    status: "APPROVED",
  },
];

export const AGGREGATOR_SERVICES: AggregatorServiceHealth[] = [
  {
    serviceId: "srv-01",
    serviceName: "Providus Bank NIP Settlement Node (Nigeria)",
    category: "SETTLEMENT_NODE",
    country: "NG",
    status: "AVAILABLE",
    uptimePercentage: 99.98,
    averageLatencyMs: 142,
    providerNode: "Providus Bank Core",
  },
  {
    serviceId: "srv-02",
    serviceName: "Koris Bank BCEAO RTGS Node (Niger Republic)",
    category: "SETTLEMENT_NODE",
    country: "NE",
    status: "AVAILABLE",
    uptimePercentage: 99.85,
    averageLatencyMs: 220,
    providerNode: "Koris Bank Core",
  },
  {
    serviceId: "srv-03",
    serviceName: "Dynamic Virtual NUBAN Direct Credit Gateway",
    category: "BANK_TRANSFER",
    country: "NG",
    status: "AVAILABLE",
    uptimePercentage: 99.99,
    averageLatencyMs: 88,
    providerNode: "Providus Bank API Gateway",
  },
  {
    serviceId: "srv-04",
    serviceName: "PAX / Sunmi Agency POS Terminal Switching",
    category: "CARD_POS",
    country: "NG",
    status: "AVAILABLE",
    uptimePercentage: 99.91,
    averageLatencyMs: 310,
    providerNode: "Interswitch / NIBSS",
  },
];

export const AGGREGATOR_TEAM: AggregatorTeamMember[] = [
  {
    id: "team-01",
    fullName: "Alhaji Sani Bello",
    email: "sani.bello@sahel-syndicate.ng",
    phone: "+234 803 123 4567",
    role: "AGGREGATOR_OWNER",
    territoryScope: ["ALL"],
    status: "ACTIVE",
    lastLoginAt: "2026-09-03T11:30:00Z",
    permissions: ["ALL_ACCESS", "AUTHORIZE_LIQUIDITY_DISPATCH", "VIEW_FINANCIALS", "MANAGE_TEAM"],
  },
  {
    id: "team-02",
    fullName: "Hadiza Umar Faruk",
    email: "hadiza.finance@sahel-syndicate.ng",
    phone: "+234 802 991 2233",
    role: "FINANCE_MANAGER",
    territoryScope: ["ALL"],
    status: "ACTIVE",
    lastLoginAt: "2026-09-03T09:45:00Z",
    permissions: ["VIEW_FINANCIALS", "AUTHORIZE_LIQUIDITY_DISPATCH", "VIEW_SETTLEMENTS", "RECONCILIATION_MATCH"],
  },
  {
    id: "team-03",
    fullName: "Musa Dan-Ali",
    email: "musa.ops@sahel-syndicate.ng",
    phone: "+234 809 110 9988",
    role: "OPERATIONS_MANAGER",
    territoryScope: ["Kano North & Urban", "Kaduna Metro"],
    status: "ACTIVE",
    lastLoginAt: "2026-09-03T11:00:00Z",
    permissions: ["VIEW_AGENTS", "MANAGE_AGENTS", "VIEW_MERCHANTS", "RESOLVE_EXCEPTIONS"],
  },
];

export const AGGREGATOR_TARGETS: AggregatorTarget[] = [
  {
    id: "tgt-01",
    title: "Q3 2026 Monthly TPV Milestone",
    metricType: "TPV",
    targetValue: 2000000000,
    currentActual: 1845000000,
    unit: "NGN",
    period: "MONTHLY_Q3_2026",
    deadline: "2026-09-30",
  },
  {
    id: "tgt-02",
    title: "Active Verified Agency Network Nodes",
    metricType: "ACTIVE_AGENTS",
    targetValue: 300,
    currentActual: 248,
    unit: "Agents",
    period: "MONTHLY_Q3_2026",
    deadline: "2026-09-30",
  },
  {
    id: "tgt-03",
    title: "Wholesale Merchant Acquiring Portfolio",
    metricType: "NEW_MERCHANTS",
    targetValue: 100,
    currentActual: 84,
    unit: "Merchants",
    period: "MONTHLY_Q3_2026",
    deadline: "2026-09-30",
  },
];
