import {
  DeveloperOrganization,
  DeveloperMember,
  DeveloperApplication,
  ApiCredential,
  ApiProduct,
  ApiEndpoint,
  WebhookEndpoint,
  WebhookDeliveryLog,
  WebhookEventDef,
  ApiRequestLog,
  ErrorAnalyticsSummary,
  RateLimitQuota,
  SystemStatusNode,
  PlatformIncident,
  SdkPackage,
  IntegrationChecklistItem,
  ProductionAccessRequest,
  DeveloperSupportCase,
  DeveloperAuditLog,
} from '@/types/developer';

// 1. Authoritative Organization Fixture
export const initialOrganization: DeveloperOrganization = {
  id: 'org_kor_99182',
  name: 'Sahel Global Technologies Ltd',
  slug: 'sahel-global-tech',
  country: 'CROSS_BORDER',
  jurisdiction: 'Bilateral WAEMU',
  businessType: 'FINTECH',
  verificationStatus: 'VERIFIED',
  tier: 'ENTERPRISE',
  createdAt: '2026-01-14T08:30:00Z',
  defaultCurrency: 'NGN',
};

// 2. Team Members
export const initialMembers: DeveloperMember[] = [
  {
    id: 'usr_dev_01',
    orgId: 'org_kor_99182',
    name: 'Ibrahim Abubakar',
    email: 'i.abubakar@saheltech.io',
    role: 'OWNER',
    status: 'ACTIVE',
    mfaEnabled: true,
    lastLogin: '2026-09-03T14:15:22Z',
    avatarUrl: '/avatars/ibrahim.jpg',
  },
  {
    id: 'usr_dev_02',
    orgId: 'org_kor_99182',
    name: 'Amina Bello, Lead Architect',
    email: 'amina.bello@saheltech.io',
    role: 'ADMIN',
    status: 'ACTIVE',
    mfaEnabled: true,
    lastLogin: '2026-09-03T15:40:10Z',
  },
  {
    id: 'usr_dev_03',
    orgId: 'org_kor_99182',
    name: 'Moussa Seydou, Integration Engineer',
    email: 'm.seydou@saheltech.io',
    role: 'DEVELOPER',
    status: 'ACTIVE',
    mfaEnabled: true,
    lastLogin: '2026-09-03T11:02:45Z',
  },
  {
    id: 'usr_dev_04',
    orgId: 'org_kor_99182',
    name: 'Chinedu Eze, QA Analyst',
    email: 'c.eze@saheltech.io',
    role: 'ANALYST',
    status: 'ACTIVE',
    mfaEnabled: false,
    lastLogin: '2026-09-02T16:20:00Z',
  },
];

// 3. Applications
export const initialApplications: DeveloperApplication[] = [
  {
    id: 'app_sand_88201',
    orgId: 'org_kor_99182',
    name: 'Sahel Cross-Border Mobile Hub (Sandbox)',
    description: 'Bilateral remittance & retail merchant checkout simulator for Lagos & Niamey retail branches.',
    environment: 'SANDBOX',
    status: 'ACTIVE',
    enabledApis: ['payments', 'wallets', 'customers', 'kyc', 'merchant', 'agency', 'bills', 'fx_cross_border'],
    scopes: ['payments:read', 'payments:write', 'transfers:write', 'wallets:read', 'wallets:write', 'webhooks:write', 'kyc:read'],
    ipWhitelist: ['197.210.84.12', '102.89.34.190', '160.154.20.5'],
    rateLimitPerMinute: 600,
    monthlyRequestQuota: 2500000,
    createdAt: '2026-01-15T10:00:00Z',
    lastUsedAt: '2026-09-03T16:10:00Z',
  },
  {
    id: 'app_prod_99402',
    orgId: 'org_kor_99182',
    name: 'Sahel Cross-Border Production Gateway',
    description: 'Live bilateral NGN / XOF commercial clearing and Providus Bank NIP outward routing pipeline.',
    environment: 'PRODUCTION',
    status: 'ACTIVE',
    enabledApis: ['payments', 'wallets', 'customers', 'merchant', 'fx_cross_border'],
    scopes: ['payments:read', 'payments:write', 'transfers:write', 'wallets:read', 'webhooks:write'],
    ipWhitelist: ['197.210.84.12', '197.210.84.13', '160.154.20.10'],
    rateLimitPerMinute: 2400,
    monthlyRequestQuota: 10000000,
    createdAt: '2026-03-01T09:00:00Z',
    lastUsedAt: '2026-09-03T16:12:30Z',
  },
];

// 4. API Credentials
export const initialCredentials: ApiCredential[] = [
  {
    id: 'cred_sand_01',
    appId: 'app_sand_88201',
    orgId: 'org_kor_99182',
    name: 'Primary Sandbox Full-Access Key',
    type: 'SECRET_KEY',
    environment: 'SANDBOX',
    publicKey: 'pk_test_884920a1b2c3d4e5f6g7h8i9j0k1l2m3',
    secretKeyMasked: 'kp_test_••••••••••••••••••••••••3829fa01',
    scopes: ['payments:*', 'wallets:*', 'customers:*', 'kyc:*', 'agency:*', 'fx:*'],
    status: 'ACTIVE',
    createdAt: '2026-01-15T10:05:00Z',
    lastUsedAt: '2026-09-03T16:10:00Z',
    createdByName: 'Amina Bello',
  },
  {
    id: 'cred_prod_01',
    appId: 'app_prod_99402',
    orgId: 'org_kor_99182',
    name: 'Production Primary Secret Key',
    type: 'SECRET_KEY',
    environment: 'PRODUCTION',
    publicKey: 'pk_live_992817a02b1c3d4e5f6a7b8c9d0e1f2a',
    secretKeyMasked: 'kp_live_••••••••••••••••••••••••8912ef34',
    scopes: ['payments:read', 'payments:write', 'transfers:write', 'wallets:read'],
    status: 'ACTIVE',
    createdAt: '2026-03-01T09:30:00Z',
    lastUsedAt: '2026-09-03T16:12:30Z',
    createdByName: 'Ibrahim Abubakar',
  },
  {
    id: 'cred_sand_02',
    appId: 'app_sand_88201',
    orgId: 'org_kor_99182',
    name: 'Rotating Sandbox Key (Grace Period)',
    type: 'SECRET_KEY',
    environment: 'SANDBOX',
    publicKey: 'pk_test_110293a9b8c7d6e5f4g3h2i1j0k9l8m7',
    secretKeyMasked: 'kp_test_••••••••••••••••••••••••9948ba22',
    scopes: ['payments:read', 'payments:write'],
    status: 'ROTATING',
    createdAt: '2026-08-25T14:00:00Z',
    gracePeriodExpiresAt: '2026-09-10T23:59:59Z',
    lastUsedAt: '2026-09-01T10:15:00Z',
    createdByName: 'Moussa Seydou',
  },
];

// 5. Authoritative API Products Catalog
export const apiProducts: ApiProduct[] = [
  {
    id: 'payments',
    category: 'payments',
    name: 'Payments & Settlement Engine',
    title: 'Cross-Border, Interbank & Instant Checkout APIs',
    description: 'High-throughput payment orchestration across Providus Bank Nigeria (NIP) and Coris Bank Niger Republic (WAEMU RTGS).',
    version: 'v1.4.0',
    status: 'PRODUCTION',
    baseUrl: {
      sandbox: 'https://sandbox.koriepay.com/v1',
      production: 'https://api.koriepay.com/v1',
    },
    scopes: ['payments:read', 'payments:write', 'transfers:write', 'settlements:read'],
    webhookEvents: ['payment.created', 'payment.processing', 'payment.successful', 'payment.failed', 'payment.reversed', 'transfer.successful', 'transfer.failed'],
    sdks: ['Node.js', 'Python', 'PHP', 'Go', 'Java', 'C#'],
    changelog: [
      {
        version: 'v1.4.0',
        date: '2026-08-15',
        summary: 'Introduced atomic bilateral corridor settlement with sub-second locks and instant WAEMU reconciliation.',
        type: 'FEATURE',
      },
      {
        version: 'v1.3.2',
        date: '2026-06-20',
        summary: 'Enhanced Providus NIP outward retry backoff and Idempotency-Key duplicate detection.',
        type: 'FIX',
      },
    ],
    endpoints: [
      {
        id: 'ep_pay_01',
        productId: 'payments',
        method: 'POST',
        path: '/v1/transfers/cross-border',
        title: 'Initiate Cross-Border Transfer',
        description: 'Initiate instant bilateral remittance between Nigeria (NGN) and Niger Republic (XOF CFA) with guaranteed FX lock and real-time beneficiary validation.',
        version: 'v1.4.0',
        requiresAuth: true,
        requiredScope: 'transfers:write',
        rateLimit: '300 requests / min',
        jurisdiction: 'ALL',
        supportedCorridors: ['NGN_TO_XOF', 'XOF_TO_NGN'],
        requestHeaders: [
          { name: 'Authorization', type: 'string', required: true, description: 'Bearer secret key (e.g., Bearer kp_test_...)', example: 'Bearer kp_test_••••••••' },
          { name: 'Content-Type', type: 'string', required: true, description: 'application/json', example: 'application/json' },
          { name: 'Idempotency-Key', type: 'string', required: true, description: 'Unique UUID v4 to protect against double debit/credit execution', example: 'idem_99281a0e-4b21-4f91-a1b2-8c9d0e1f2a34' },
        ],
        requestBodySchema: [
          { name: 'source_currency', type: 'string', required: true, description: 'Source currency code (NGN or XOF)', example: 'NGN', enum: ['NGN', 'XOF'] },
          { name: 'destination_currency', type: 'string', required: true, description: 'Target currency code (NGN or XOF)', example: 'XOF', enum: ['NGN', 'XOF'] },
          { name: 'amount', type: 'integer', required: true, description: 'Amount in minor currency units (e.g. 5000000 kobo = ₦50,000.00)', example: 5000000 },
          { name: 'reference', type: 'string', required: true, description: 'Merchant unique transaction reference', example: 'TRX-SAHEL-2026-9901' },
          { name: 'recipient', type: 'object', required: true, description: 'Beneficiary destination details', example: { name: 'Moussa Harouna', bank_code: 'KORIS_NE', account_number: '22798102391', phone: '+22790123456' } },
          { name: 'narration', type: 'string', required: false, description: 'Optional payment description', example: 'Agricultural commodity trade settlement' },
        ],
        sampleRequestBody: {
          source_currency: 'NGN',
          destination_currency: 'XOF',
          amount: 5000000,
          reference: 'TRX-SAHEL-2026-9901',
          recipient: {
            name: 'Moussa Harouna',
            bank_code: 'KORIS_NE',
            account_number: '22798102391',
            phone: '+22790123456',
          },
          narration: 'Cross-border agro wholesale invoice #4401',
        },
        responses: [
          {
            statusCode: 200,
            description: 'Transfer initiated and confirmed via bilateral liquidity node',
            body: {
              status: 'success',
              code: 'TRANSFER_SUCCESSFUL',
              message: 'Bilateral cross-border transfer processed successfully',
              data: {
                transfer_reference: 'KP-XB-20260903-88219',
                merchant_reference: 'TRX-SAHEL-2026-9901',
                source: {
                  currency: 'NGN',
                  amount: 5000000,
                  formatted_amount: '₦50,000.00',
                  fee: 25000,
                  bank_node: 'Providus Bank Nigeria',
                },
                destination: {
                  currency: 'XOF',
                  amount: 21500000,
                  formatted_amount: '21,500 CFA',
                  recipient_name: 'Moussa Harouna',
                  bank_node: 'Coris Bank Niger Republic',
                  account_number: '22798102391',
                },
                exchange_rate: 0.43,
                guaranteed_rate_lock_id: 'FX-LOCK-99120',
                settlement_status: 'COMPLETED',
                settled_at: '2026-09-03T16:15:00Z',
                idempotency_key: 'idem_99281a0e-4b21-4f91-a1b2-8c9d0e1f2a34',
              },
            },
          },
          {
            statusCode: 422,
            description: 'Validation error / Rate expired / Duplicate reference',
            body: {
              status: 'error',
              code: 'DUPLICATE_REFERENCE',
              message: 'The transaction reference TRX-SAHEL-2026-9901 has already been settled.',
              request_id: 'KP-REQ-99281a4b',
            },
          },
        ],
        errorCodes: [
          { code: 'INSUFFICIENT_FUNDS', httpStatus: 400, message: 'Source wallet balance is insufficient for amount + fee.', recommendedAction: 'Top up source wallet balance before retrying.', category: 'LEDGER' },
          { code: 'RATE_LOCK_EXPIRED', httpStatus: 422, message: 'The locked FX corridor rate has expired.', recommendedAction: 'Call /v1/fx/quote to obtain a fresh rate lock ID.', category: 'PROVIDER' },
          { code: 'DUPLICATE_IDEMPOTENCY_KEY', httpStatus: 409, message: 'An operation with this Idempotency-Key is currently processing or already committed.', recommendedAction: 'Query transaction status using GET /v1/payments/{reference}/verify.', category: 'LEDGER' },
        ],
      },
      {
        id: 'ep_pay_02',
        productId: 'payments',
        method: 'GET',
        path: '/v1/payments/{reference}/verify',
        title: 'Verify Payment / Transfer Status',
        description: 'Query authoritative switch and core ledger status for any transaction reference.',
        version: 'v1.4.0',
        requiresAuth: true,
        requiredScope: 'payments:read',
        rateLimit: '1200 requests / min',
        jurisdiction: 'ALL',
        requestHeaders: [
          { name: 'Authorization', type: 'string', required: true, description: 'Bearer secret key', example: 'Bearer kp_test_••••••••' },
        ],
        queryParams: [
          { name: 'reference', type: 'string', required: true, description: 'Merchant reference or KoriePay transaction reference', example: 'TRX-SAHEL-2026-9901' },
        ],
        responses: [
          {
            statusCode: 200,
            description: 'Transaction status retrieved',
            body: {
              status: 'success',
              data: {
                reference: 'TRX-SAHEL-2026-9901',
                koriepay_reference: 'KP-XB-20260903-88219',
                status: 'SUCCESSFUL',
                amount: 5000000,
                currency: 'NGN',
                channel: 'CROSS_BORDER_CORRIDOR',
                paid_at: '2026-09-03T16:15:00Z',
                provider_response_code: '00',
              },
            },
          },
        ],
        errorCodes: [
          { code: 'TRANSACTION_NOT_FOUND', httpStatus: 404, message: 'No transaction exists with the supplied reference.', recommendedAction: 'Check reference string or verify environment (Sandbox vs Production).', category: 'VALIDATION' },
        ],
      },
      {
        id: 'ep_pay_03',
        productId: 'payments',
        method: 'POST',
        path: '/v2/nip-gateway/outward',
        title: 'Providus NIP Outward Interbank Transfer (NGN)',
        description: 'Direct integration with Providus Bank NIP outward instant credit switch for all 90+ Nigerian commercial banks.',
        version: 'v2.1.0',
        requiresAuth: true,
        requiredScope: 'transfers:write',
        rateLimit: '300 requests / min',
        jurisdiction: 'NG',
        requestHeaders: [
          { name: 'Authorization', type: 'string', required: true, description: 'Bearer secret key', example: 'Bearer kp_test_••••••••' },
          { name: 'Idempotency-Key', type: 'string', required: true, description: 'Unique UUID v4', example: 'idem_prov_00192a' },
        ],
        sampleRequestBody: {
          destination_bank_code: '000013',
          destination_account_number: '0123456789',
          beneficiary_name: 'Adewale Johnson',
          amount: 15000000,
          currency: 'NGN',
          reference: 'NIP-OUT-99201',
          narration: 'Vendor invoice payment',
        },
        responses: [
          {
            statusCode: 200,
            description: 'NIP Outward dispatch committed',
            body: {
              status: 'success',
              data: {
                session_id: '99901326090316150012938102',
                reference: 'NIP-OUT-99201',
                providus_reference: 'PROV-NIP-88201',
                response_code: '00',
                response_message: 'Approved or completed successfully',
                amount: 15000000,
                settled_at: '2026-09-03T16:15:22Z',
              },
            },
          },
        ],
        errorCodes: [
          { code: 'INVALID_NUBAN', httpStatus: 422, message: 'Account number could not be validated with destination bank.', recommendedAction: 'Run name enquiry first before executing outward dispatch.', category: 'VALIDATION' },
        ],
      },
    ],
  },
  {
    id: 'merchant',
    category: 'merchant',
    name: 'Merchant Checkout & Dynamic Accounts',
    title: 'Virtual NUBANs, Standee Dynamic QR & Collections',
    description: 'Providus Bank dedicated virtual NUBANs, dynamic standee QR checkout, and auto-settlement engines for merchants.',
    version: 'v1.4.0',
    status: 'PRODUCTION',
    baseUrl: {
      sandbox: 'https://sandbox.koriepay.com/v1/merchant',
      production: 'https://api.koriepay.com/v1/merchant',
    },
    scopes: ['merchant:read', 'merchant:write', 'checkout:create'],
    webhookEvents: ['checkout.session.completed', 'virtual_account.credited', 'settlement.dispatched'],
    sdks: ['Node.js', 'Python', 'PHP', 'Go'],
    changelog: [
      { version: 'v1.4.0', date: '2026-07-10', summary: 'Added instant dynamic QR code generation with EMVCo compatibility.', type: 'FEATURE' },
    ],
    endpoints: [
      {
        id: 'ep_mer_01',
        productId: 'merchant',
        method: 'POST',
        path: '/v1/merchant/checkout',
        title: 'Initialize Dynamic Checkout Session',
        description: 'Creates a dynamic checkout session with dedicated Providus virtual account, dynamic QR payload, and hosted URL.',
        version: 'v1.4.0',
        requiresAuth: true,
        requiredScope: 'checkout:create',
        rateLimit: '600 requests / min',
        jurisdiction: 'ALL',
        requestHeaders: [
          { name: 'Authorization', type: 'string', required: true, description: 'Bearer secret key', example: 'Bearer kp_test_••••••••' },
        ],
        sampleRequestBody: {
          amount: 2500000,
          currency: 'NGN',
          customer_email: 'buyer@example.ng',
          customer_name: 'Fatima Garba',
          reference: 'ORD-2026-99042',
          callback_url: 'https://myshop.ng/checkout/callback',
        },
        responses: [
          {
            statusCode: 201,
            description: 'Checkout session created',
            body: {
              status: 'success',
              data: {
                reference: 'ORD-2026-99042',
                checkout_url: 'https://pay.koriepay.com/checkout/ORD-2026-99042',
                virtual_account: {
                  bank_name: 'Providus Bank',
                  account_number: '9928193820',
                  account_name: 'KORIE / SAHEL / FATIMA GARBA',
                  expires_at: '2026-09-03T23:59:59Z',
                },
                qr_code_data: 'koriepay://pay?ref=ORD-2026-99042&acc=9928193820&amt=2500000',
              },
            },
          },
        ],
        errorCodes: [
          { code: 'INVALID_AMOUNT', httpStatus: 400, message: 'Amount must be a positive integer in kobo/minor units.', recommendedAction: 'Ensure amount is integer >= 100.', category: 'VALIDATION' },
        ],
      },
      {
        id: 'ep_mer_02',
        productId: 'merchant',
        method: 'POST',
        path: '/v1/merchant/accounts/virtual',
        title: 'Provision Dedicated Virtual NUBAN',
        description: 'Instantly allocate permanent or dynamic collection virtual accounts tied to Providus Bank or Coris Bank.',
        version: 'v1.4.0',
        requiresAuth: true,
        requiredScope: 'merchant:write',
        rateLimit: '300 requests / min',
        jurisdiction: 'ALL',
        requestHeaders: [{ name: 'Authorization', type: 'string', required: true, description: 'Bearer key', example: 'Bearer kp_test_••••••••' }],
        sampleRequestBody: {
          customer_id: 'cust_88201',
          currency: 'NGN',
          bvn: '22198102391',
          account_type: 'PERMANENT',
        },
        responses: [
          {
            statusCode: 200,
            description: 'Virtual account allocated',
            body: {
              status: 'success',
              data: {
                bank_name: 'Providus Bank',
                bank_code: '000023',
                account_number: '9938102948',
                account_name: 'KORIE / SAHEL TECH / CUST-88201',
                currency: 'NGN',
                status: 'ACTIVE',
              },
            },
          },
        ],
        errorCodes: [
          { code: 'BVN_VERIFICATION_FAILED', httpStatus: 422, message: 'The BVN provided does not match customer profile.', recommendedAction: 'Verify BVN with customer identity document.', category: 'COMPLIANCE' },
        ],
      },
    ],
  },
  {
    id: 'wallets',
    category: 'wallets',
    name: 'Multi-Currency Ledger & Wallet API',
    title: 'Institutional & Customer Wallet Operations',
    description: 'Double-entry ledger wallets supporting NGN, XOF, USD hold vaults, sub-accounts, and escrow locking.',
    version: 'v1.3.0',
    status: 'PRODUCTION',
    baseUrl: {
      sandbox: 'https://sandbox.koriepay.com/v1/wallets',
      production: 'https://api.koriepay.com/v1/wallets',
    },
    scopes: ['wallets:read', 'wallets:write'],
    webhookEvents: ['wallet.credited', 'wallet.debited', 'wallet.hold_placed', 'wallet.hold_released'],
    sdks: ['Node.js', 'Python', 'Go'],
    changelog: [
      { version: 'v1.3.0', date: '2026-05-18', summary: 'Added multi-currency escrow hold locking capabilities.', type: 'FEATURE' },
    ],
    endpoints: [
      {
        id: 'ep_wal_01',
        productId: 'wallets',
        method: 'POST',
        path: '/v1/wallets/create',
        title: 'Create Multi-Currency Wallet',
        description: 'Provisions an immutable double-entry sub-ledger account for an end-user or merchant sub-unit.',
        version: 'v1.3.0',
        requiresAuth: true,
        requiredScope: 'wallets:write',
        rateLimit: '300 requests / min',
        jurisdiction: 'ALL',
        requestHeaders: [{ name: 'Authorization', type: 'string', required: true, description: 'Bearer key', example: 'Bearer kp_test_••••••••' }],
        sampleRequestBody: {
          customer_id: 'cust_88201',
          currency: 'NGN',
          wallet_tier: 'TIER_2',
          label: 'Primary Operational Wallet',
        },
        responses: [
          {
            statusCode: 201,
            description: 'Wallet created',
            body: {
              status: 'success',
              data: {
                wallet_id: 'wal_ngn_99182',
                currency: 'NGN',
                balance: 0,
                ledger_balance: 0,
                status: 'ACTIVE',
                created_at: '2026-09-03T16:15:00Z',
              },
            },
          },
        ],
        errorCodes: [
          { code: 'MAX_WALLETS_EXCEEDED', httpStatus: 400, message: 'Customer has reached max allowed wallets for their KYC tier.', recommendedAction: 'Upgrade customer KYC tier to TIER_3.', category: 'COMPLIANCE' },
        ],
      },
      {
        id: 'ep_wal_02',
        productId: 'wallets',
        method: 'GET',
        path: '/v1/wallets/{id}/balance',
        title: 'Retrieve Real-Time Balance',
        description: 'Returns confirmed available balance, ledger balance, and pending hold locks.',
        version: 'v1.3.0',
        requiresAuth: true,
        requiredScope: 'wallets:read',
        rateLimit: '1200 requests / min',
        jurisdiction: 'ALL',
        requestHeaders: [{ name: 'Authorization', type: 'string', required: true, description: 'Bearer key', example: 'Bearer kp_test_••••••••' }],
        responses: [
          {
            statusCode: 200,
            description: 'Wallet balance returned',
            body: {
              status: 'success',
              data: {
                wallet_id: 'wal_ngn_99182',
                currency: 'NGN',
                available_balance: 84500000,
                ledger_balance: 85000000,
                locked_hold_amount: 500000,
                formatted_available: '₦845,000.00',
              },
            },
          },
        ],
        errorCodes: [
          { code: 'WALLET_NOT_FOUND', httpStatus: 404, message: 'Wallet id does not exist in ledger.', recommendedAction: 'Check wallet id format.', category: 'VALIDATION' },
        ],
      },
    ],
  },
  {
    id: 'agency',
    category: 'agency',
    name: 'Agency Banking & Smart POS Switch',
    title: 'Cash-In, Cash-Out & Terminal Fleet Control',
    description: 'Biometric Android POS terminal communication, agency liquidity rebalancing, and agent commissions.',
    version: 'v1.2.0',
    status: 'PRODUCTION',
    baseUrl: {
      sandbox: 'https://sandbox.koriepay.com/v1/agency',
      production: 'https://api.koriepay.com/v1/agency',
    },
    scopes: ['agency:read', 'agency:write', 'terminals:manage'],
    webhookEvents: ['agency.cash_in.completed', 'agency.cash_out.completed', 'terminal.heartbeat_lost'],
    sdks: ['Node.js', 'Java', 'Android SDK'],
    changelog: [
      { version: 'v1.2.0', date: '2026-06-01', summary: 'Added offline cache signing for remote rural agency banking terminals.', type: 'FEATURE' },
    ],
    endpoints: [
      {
        id: 'ep_agn_01',
        productId: 'agency',
        method: 'POST',
        path: '/v1/agency/cash-out',
        title: 'Authorize Terminal Cash Withdrawal',
        description: 'Authorizes agent terminal cash withdrawal with instant agent wallet credit and customer card/account debit.',
        version: 'v1.2.0',
        requiresAuth: true,
        requiredScope: 'agency:write',
        rateLimit: '300 requests / min',
        jurisdiction: 'ALL',
        requestHeaders: [{ name: 'Authorization', type: 'string', required: true, description: 'Bearer key', example: 'Bearer kp_test_••••••••' }],
        sampleRequestBody: {
          terminal_id: 'TERM-POS-NGN-0041',
          agent_id: 'agt_kano_012',
          amount: 1000000,
          currency: 'NGN',
          auth_token: 'EMV_PINBLOCK_••••',
          reference: 'POS-TX-99120',
        },
        responses: [
          {
            statusCode: 200,
            description: 'Cash-out authorized',
            body: {
              status: 'success',
              data: {
                reference: 'POS-TX-99120',
                auth_code: 'APPRV-88201',
                agent_commission: 15000,
                agent_wallet_credited: true,
                terminal_receipt_text: 'KORIEPAY CASH-OUT APPROVED\nREF: POS-TX-99120\nAMT: NGN 10,000.00',
              },
            },
          },
        ],
        errorCodes: [
          { code: 'TERMINAL_NOT_REGISTERED', httpStatus: 403, message: 'Terminal serial is not bound to active agent.', recommendedAction: 'Re-bind terminal via Aggregator or Admin portal.', category: 'AUTH' },
        ],
      },
    ],
  },
  {
    id: 'fx_cross_border',
    category: 'fx_cross_border',
    name: 'FX Corridor & Treasury Liquidity',
    title: 'Indicative Rates, Guaranteed Rate Locks & Bilateral Settlement',
    description: 'Real-time bilateral pricing between Nigerian Naira (NGN) and West African CFA Franc (XOF) with 60-second rate locks.',
    version: 'v1.4.0',
    status: 'PRODUCTION',
    baseUrl: {
      sandbox: 'https://sandbox.koriepay.com/v1/fx',
      production: 'https://api.koriepay.com/v1/fx',
    },
    scopes: ['fx:read', 'fx:quote', 'fx:execute'],
    webhookEvents: ['fx.rate_updated', 'fx.liquidity_alert'],
    sdks: ['Node.js', 'Python', 'Go'],
    changelog: [
      { version: 'v1.4.0', date: '2026-08-01', summary: 'Added WAEMU central bank benchmark rate parity stream.', type: 'FEATURE' },
    ],
    endpoints: [
      {
        id: 'ep_fx_01',
        productId: 'fx_cross_border',
        method: 'GET',
        path: '/v1/fx/corridor-rates',
        title: 'Get Real-Time Bilateral Corridor Rates',
        description: 'Returns real-time mid-market rates, spread percentages, and liquidity pool depth for NGN/XOF corridor.',
        version: 'v1.4.0',
        requiresAuth: true,
        requiredScope: 'fx:read',
        rateLimit: '1200 requests / min',
        jurisdiction: 'ALL',
        requestHeaders: [{ name: 'Authorization', type: 'string', required: true, description: 'Bearer key', example: 'Bearer kp_test_••••••••' }],
        responses: [
          {
            statusCode: 200,
            description: 'Corridor rates retrieved',
            body: {
              status: 'success',
              data: {
                corridor: 'NGN_XOF',
                timestamp: '2026-09-03T16:15:00Z',
                ngn_to_xof: {
                  rate: 0.43,
                  inverse: 2.325,
                  spread_bps: 18,
                  market_status: 'OPEN',
                  liquidity_level: 'HIGH',
                },
                xof_to_ngn: {
                  rate: 2.31,
                  inverse: 0.432,
                  spread_bps: 18,
                  market_status: 'OPEN',
                  liquidity_level: 'HIGH',
                },
              },
            },
          },
        ],
        errorCodes: [
          { code: 'CORRIDOR_SUSPENDED', httpStatus: 503, message: 'Corridor trading is temporarily paused for treasury maintenance.', recommendedAction: 'Check /status page for updates.', category: 'PROVIDER' },
        ],
      },
    ],
  },
  {
    id: 'kyc',
    category: 'kyc',
    name: 'KYC / KYB & Compliance Verification',
    title: 'NIN, BVN, NIF, CAC & AML Screening APIs',
    description: 'Instant regulatory identity verification across Nigeria (NIBSS BVN, NIMC NIN, CAC) and Niger Republic (NIF, NNI, RCCM).',
    version: 'v1.1.0',
    status: 'PRODUCTION',
    baseUrl: {
      sandbox: 'https://sandbox.koriepay.com/v1/kyc',
      production: 'https://api.koriepay.com/v1/kyc',
    },
    scopes: ['kyc:read', 'kyc:verify'],
    webhookEvents: ['kyc.verification.completed', 'kyc.verification.failed', 'sanctions.match_detected'],
    sdks: ['Node.js', 'Python'],
    changelog: [
      { version: 'v1.1.0', date: '2026-04-12', summary: 'Added automated WAEMU CENTIF sanctions cross-check.', type: 'FEATURE' },
    ],
    endpoints: [
      {
        id: 'ep_kyc_01',
        productId: 'kyc',
        method: 'POST',
        path: '/v1/kyc/verify-identity',
        title: 'Verify National Identity / BVN / NIF',
        description: 'Authoritative biometric or alphanumeric identity lookup matching regulatory databases in Nigeria and Niger Republic.',
        version: 'v1.1.0',
        requiresAuth: true,
        requiredScope: 'kyc:verify',
        rateLimit: '120 requests / min',
        jurisdiction: 'ALL',
        requestHeaders: [{ name: 'Authorization', type: 'string', required: true, description: 'Bearer key', example: 'Bearer kp_test_••••••••' }],
        sampleRequestBody: {
          country: 'NG',
          id_type: 'BVN',
          id_number: '22198102391',
          first_name: 'Ibrahim',
          last_name: 'Abubakar',
          dob: '1988-05-14',
        },
        responses: [
          {
            statusCode: 200,
            description: 'Identity verification result',
            body: {
              status: 'success',
              data: {
                match_status: 'EXACT_MATCH',
                confidence_score: 99.4,
                name_match: true,
                dob_match: true,
                sanctions_pep_clean: true,
                verification_id: 'KYC-VER-99210',
              },
            },
          },
        ],
        errorCodes: [
          { code: 'IDENTITY_RECORD_MISMATCH', httpStatus: 422, message: 'Supplied name/DOB does not match national registry record.', recommendedAction: 'Prompt user to review spelt name.', category: 'COMPLIANCE' },
        ],
      },
    ],
  },
  {
    id: 'customers',
    category: 'customers',
    name: 'Customer 360° & Identity Directory',
    title: 'Customer Onboarding, Profiles & Beneficiaries',
    description: 'Unified customer profiles across mobile wallets, merchant customers, and agency banking accounts.',
    version: 'v1.2.0',
    status: 'PRODUCTION',
    baseUrl: {
      sandbox: 'https://sandbox.koriepay.com/v1/customers',
      production: 'https://api.koriepay.com/v1/customers',
    },
    scopes: ['customers:read', 'customers:write'],
    webhookEvents: ['customer.created', 'customer.tier_upgraded', 'customer.frozen'],
    sdks: ['Node.js', 'Python', 'Go'],
    changelog: [
      { version: 'v1.2.0', date: '2026-03-22', summary: 'Added multi-language preference profile fields (en, ha, fr).', type: 'FEATURE' },
    ],
    endpoints: [
      {
        id: 'ep_cust_01',
        productId: 'customers',
        method: 'POST',
        path: '/v1/customers',
        title: 'Create Customer Profile',
        description: 'Creates a verified customer entity in the KoriePay directory with tier 1 wallet limits.',
        version: 'v1.2.0',
        requiresAuth: true,
        requiredScope: 'customers:write',
        rateLimit: '300 requests / min',
        jurisdiction: 'ALL',
        requestHeaders: [{ name: 'Authorization', type: 'string', required: true, description: 'Bearer key', example: 'Bearer kp_test_••••••••' }],
        sampleRequestBody: {
          first_name: 'Halima',
          last_name: 'Usman',
          email: 'halima.usman@example.ng',
          phone: '+2348039281734',
          country: 'NG',
          preferred_language: 'ha',
        },
        responses: [
          {
            statusCode: 201,
            description: 'Customer created',
            body: {
              status: 'success',
              data: {
                customer_id: 'cust_ng_88201',
                kyc_tier: 'TIER_1',
                daily_limit_ngn: 5000000,
                created_at: '2026-09-03T16:15:00Z',
              },
            },
          },
        ],
        errorCodes: [
          { code: 'PHONE_ALREADY_EXISTS', httpStatus: 409, message: 'A customer profile with this phone number already exists.', recommendedAction: 'Look up existing customer using GET /v1/customers/lookup.', category: 'VALIDATION' },
        ],
      },
    ],
  },
  {
    id: 'bills',
    category: 'bills',
    name: 'Utility Bills, Airtime & VAS',
    title: 'Electricity DisCos, Airtime & Data Services',
    description: 'Real-time bill payment and airtime vending across Nigerian DisCos (IKEDC, EKEDC, AEDC, KEDCO) and Nigerien telcos (Airtel, Zamani, Moov).',
    version: 'v1.1.0',
    status: 'PRODUCTION',
    baseUrl: {
      sandbox: 'https://sandbox.koriepay.com/v1/bills',
      production: 'https://api.koriepay.com/v1/bills',
    },
    scopes: ['bills:read', 'bills:vend'],
    webhookEvents: ['bill.vend.completed', 'bill.vend.failed'],
    sdks: ['Node.js', 'Python', 'PHP'],
    changelog: [
      { version: 'v1.1.0', date: '2026-02-14', summary: 'Added token generation and recharge verification API.', type: 'FEATURE' },
    ],
    endpoints: [
      {
        id: 'ep_bill_01',
        productId: 'bills',
        method: 'POST',
        path: '/v1/bills/electricity',
        title: 'Vend Prepaid Electricity Token',
        description: 'Validates meter number with the utility provider and dispenses a prepaid recharge token immediately.',
        version: 'v1.1.0',
        requiresAuth: true,
        requiredScope: 'bills:vend',
        rateLimit: '300 requests / min',
        jurisdiction: 'ALL',
        requestHeaders: [{ name: 'Authorization', type: 'string', required: true, description: 'Bearer key', example: 'Bearer kp_test_••••••••' }],
        sampleRequestBody: {
          provider_code: 'KEDCO_PREPAID',
          meter_number: '45091823901',
          amount: 500000,
          customer_phone: '+2348039281734',
        },
        responses: [
          {
            statusCode: 200,
            description: 'Electricity token dispensed',
            body: {
              status: 'success',
              data: {
                token: '4829-0192-3849-1029-4820',
                units_kwh: 64.2,
                meter_number: '45091823901',
                customer_name: 'Malam Garba Shehu',
                receipt_number: 'KEDCO-RCT-99120',
              },
            },
          },
        ],
        errorCodes: [
          { code: 'METER_INVALID', httpStatus: 422, message: 'Meter number is inactive or not found with DisCo.', recommendedAction: 'Confirm meter serial with customer.', category: 'PROVIDER' },
        ],
      },
    ],
  },
];

// 6. Webhook Subscriptions
export const initialWebhooks: WebhookEndpoint[] = [
  {
    id: 'whk_sand_01',
    appId: 'app_sand_88201',
    orgId: 'org_kor_99182',
    url: 'https://webhook.saheltech.io/sandbox/koriepay-events',
    environment: 'SANDBOX',
    status: 'ACTIVE',
    events: ['payment.successful', 'payment.failed', 'transfer.successful', 'transfer.failed', 'virtual_account.credited'],
    signingSecretMasked: 'whsec_••••••••••••••••••••••••3821a9',
    failureCount: 0,
    lastDeliveryStatus: 'DELIVERED',
    lastDeliveredAt: '2026-09-03T16:12:00Z',
    createdAt: '2026-01-16T11:00:00Z',
    retryPolicy: 'STANDARD_EXPONENTIAL',
  },
  {
    id: 'whk_prod_01',
    appId: 'app_prod_99402',
    orgId: 'org_kor_99182',
    url: 'https://core.saheltech.io/api/v1/webhooks/koriepay',
    environment: 'PRODUCTION',
    status: 'ACTIVE',
    events: ['payment.successful', 'transfer.successful', 'settlement.dispatched'],
    signingSecretMasked: 'whsec_••••••••••••••••••••••••9941bc',
    failureCount: 0,
    lastDeliveryStatus: 'DELIVERED',
    lastDeliveredAt: '2026-09-03T16:10:45Z',
    createdAt: '2026-03-01T10:00:00Z',
    retryPolicy: 'AGGRESSIVE',
  },
];

// 7. Webhook Delivery Logs
export const initialWebhookLogs: WebhookDeliveryLog[] = [
  {
    id: 'wlog_99101',
    webhookId: 'whk_sand_01',
    event: 'payment.successful',
    endpointUrl: 'https://webhook.saheltech.io/sandbox/koriepay-events',
    environment: 'SANDBOX',
    attemptNumber: 1,
    maxAttempts: 5,
    httpStatus: 200,
    latencyMs: 142,
    status: 'DELIVERED',
    idempotencyKey: 'idem_evt_99101',
    signatureHeader: 't=1788430500,v1=98f12a8849b2c0192e48271a0b3f81e62194c278912ba09148b192e817492c10',
    payload: {
      event: 'payment.successful',
      event_id: 'EVT-KP-20260903-00912',
      timestamp: 1788430500,
      data: {
        reference: 'ORD-2026-99042',
        amount: 2500000,
        currency: 'NGN',
        status: 'SUCCESSFUL',
        paid_at: '2026-09-03T16:12:00Z',
        channel: 'BANK_TRANSFER_VIRTUAL_NUBAN',
        bank_node: 'Providus Bank Nigeria',
      },
    },
    responseBody: '{"received": true, "processed_order": "ORD-2026-99042"}',
    timestamp: '2026-09-03T16:12:01Z',
  },
  {
    id: 'wlog_99102',
    webhookId: 'whk_sand_01',
    event: 'transfer.successful',
    endpointUrl: 'https://webhook.saheltech.io/sandbox/koriepay-events',
    environment: 'SANDBOX',
    attemptNumber: 1,
    maxAttempts: 5,
    httpStatus: 200,
    latencyMs: 188,
    status: 'DELIVERED',
    idempotencyKey: 'idem_evt_99102',
    signatureHeader: 't=1788430440,v1=48a1290bb4e18290f12c8a001928471b629471b0281c9a81920381729381726a',
    payload: {
      event: 'transfer.successful',
      event_id: 'EVT-KP-20260903-00908',
      timestamp: 1788430440,
      data: {
        reference: 'TRX-SAHEL-2026-9901',
        transfer_reference: 'KP-XB-20260903-88219',
        source_currency: 'NGN',
        destination_currency: 'XOF',
        amount_sent: 5000000,
        amount_received: 21500000,
        recipient: 'Moussa Harouna',
        destination_bank: 'Coris Bank Niger Republic',
      },
    },
    responseBody: '{"status": "ok"}',
    timestamp: '2026-09-03T16:10:00Z',
  },
  {
    id: 'wlog_99103',
    webhookId: 'whk_sand_01',
    event: 'virtual_account.credited',
    endpointUrl: 'https://webhook.saheltech.io/sandbox/koriepay-events',
    environment: 'SANDBOX',
    attemptNumber: 2,
    maxAttempts: 5,
    httpStatus: 200,
    latencyMs: 210,
    status: 'DELIVERED',
    idempotencyKey: 'idem_evt_99103',
    signatureHeader: 't=1788429800,v1=12984920ab812903fe8192038192a09182390192a8192038192039182039182a',
    payload: {
      event: 'virtual_account.credited',
      event_id: 'EVT-KP-20260903-00845',
      timestamp: 1788429800,
      data: {
        virtual_account_number: '9928193820',
        bank_name: 'Providus Bank',
        amount: 2500000,
        currency: 'NGN',
        sender_bank: 'Access Bank Nigeria',
        sender_account_name: 'Fatima Garba',
        session_id: '99902326090315480019283019',
      },
    },
    responseBody: '{"acknowledged": true}',
    timestamp: '2026-09-03T15:50:00Z',
  },
];

// 8. Webhook Events Definitions Registry
export const webhookEventCatalog: WebhookEventDef[] = [
  {
    event: 'payment.successful',
    category: 'payments',
    description: 'Dispatched immediately when an online checkout, virtual account transfer, or POS card charge is confirmed by the settlement node.',
    jurisdiction: 'ALL',
    samplePayload: {
      event: 'payment.successful',
      event_id: 'EVT-KP-20260903-88001',
      timestamp: 1788430500,
      data: {
        reference: 'ORD-2026-99042',
        amount: 2500000,
        currency: 'NGN',
        net_amount: 2462500,
        fee: 37500,
        channel: 'BANK_TRANSFER',
        settlement_node: 'Providus Bank Nigeria',
      },
    },
  },
  {
    event: 'transfer.successful',
    category: 'payments',
    description: 'Dispatched when an outward NIP or bilateral cross-border transfer has been irrevocably credited to the beneficiary.',
    jurisdiction: 'ALL',
    samplePayload: {
      event: 'transfer.successful',
      event_id: 'EVT-KP-20260903-88002',
      timestamp: 1788430510,
      data: {
        reference: 'TRX-SAHEL-2026-9901',
        koriepay_reference: 'KP-XB-20260903-88219',
        source_amount: 5000000,
        source_currency: 'NGN',
        destination_amount: 21500000,
        destination_currency: 'XOF',
        exchange_rate: 0.43,
        destination_bank: 'Coris Bank Niger Republic',
      },
    },
  },
  {
    event: 'transfer.failed',
    category: 'payments',
    description: 'Dispatched if an outward payout was rejected by the beneficiary switch; source wallet is automatically unlocked/refunded.',
    jurisdiction: 'ALL',
    samplePayload: {
      event: 'transfer.failed',
      event_id: 'EVT-KP-20260903-88003',
      timestamp: 1788430520,
      data: {
        reference: 'TRX-SAHEL-2026-9902',
        failure_code: 'BENEFICIARY_ACCOUNT_BLOCKED',
        failure_reason: 'Recipient bank rejected outward credit due to KYC restrictions.',
        refunded_amount: 5000000,
        currency: 'NGN',
      },
    },
  },
  {
    event: 'virtual_account.credited',
    category: 'merchant',
    description: 'Dispatched when a customer transfers money into a dedicated Providus or Coris virtual NUBAN.',
    jurisdiction: 'ALL',
    samplePayload: {
      event: 'virtual_account.credited',
      event_id: 'EVT-KP-20260903-88004',
      timestamp: 1788430530,
      data: {
        virtual_account: '9928193820',
        bank_name: 'Providus Bank',
        amount: 2500000,
        currency: 'NGN',
        payer_name: 'Fatima Garba',
      },
    },
  },
  {
    event: 'kyc.verification.completed',
    category: 'kyc',
    description: 'Dispatched when an asynchronous BVN, NIN, or CAC verification process completes with verified status.',
    jurisdiction: 'ALL',
    samplePayload: {
      event: 'kyc.verification.completed',
      event_id: 'EVT-KP-20260903-88005',
      timestamp: 1788430540,
      data: {
        verification_id: 'KYC-VER-99210',
        id_type: 'BVN',
        match_status: 'EXACT_MATCH',
        confidence_score: 99.4,
      },
    },
  },
];

// 9. API Request Logs
export const initialRequestLogs: ApiRequestLog[] = [
  {
    id: 'req_log_001',
    requestId: 'KP-REQ-992810a1',
    correlationId: 'corr_sahel_99210',
    appId: 'app_sand_88201',
    appName: 'Sahel Cross-Border Mobile Hub (Sandbox)',
    environment: 'SANDBOX',
    method: 'POST',
    endpoint: '/v1/transfers/cross-border',
    statusCode: 200,
    latencyMs: 142,
    ipAddress: '197.210.84.12',
    country: 'NG',
    timestamp: '2026-09-03T16:15:00Z',
    requestHeadersMasked: {
      'Authorization': 'Bearer kp_test_••••••••••••••••••••••••3829fa01',
      'Content-Type': 'application/json',
      'Idempotency-Key': 'idem_99281a0e-4b21-4f91-a1b2-8c9d0e1f2a34',
    },
    requestBodyMasked: {
      source_currency: 'NGN',
      destination_currency: 'XOF',
      amount: 5000000,
      reference: 'TRX-SAHEL-2026-9901',
      recipient: { name: 'Moussa Harouna', bank_code: 'KORIS_NE', account_number: '22798102391' },
    },
    responseBodyMasked: {
      status: 'success',
      transfer_reference: 'KP-XB-20260903-88219',
      settlement_status: 'COMPLETED',
    },
    providerNode: 'Coris Bank NE',
  },
  {
    id: 'req_log_002',
    requestId: 'KP-REQ-992810a2',
    correlationId: 'corr_sahel_99211',
    appId: 'app_sand_88201',
    appName: 'Sahel Cross-Border Mobile Hub (Sandbox)',
    environment: 'SANDBOX',
    method: 'GET',
    endpoint: '/v1/payments/TRX-SAHEL-2026-9901/verify',
    statusCode: 200,
    latencyMs: 48,
    ipAddress: '197.210.84.12',
    country: 'NG',
    timestamp: '2026-09-03T16:15:20Z',
    requestHeadersMasked: {
      'Authorization': 'Bearer kp_test_••••••••••••••••••••••••3829fa01',
    },
    responseBodyMasked: {
      status: 'success',
      reference: 'TRX-SAHEL-2026-9901',
      status_code: 'SUCCESSFUL',
    },
  },
  {
    id: 'req_log_003',
    requestId: 'KP-REQ-992810a3',
    correlationId: 'corr_sahel_99212',
    appId: 'app_sand_88201',
    appName: 'Sahel Cross-Border Mobile Hub (Sandbox)',
    environment: 'SANDBOX',
    method: 'POST',
    endpoint: '/v1/merchant/checkout',
    statusCode: 201,
    latencyMs: 84,
    ipAddress: '102.89.34.190',
    country: 'NG',
    timestamp: '2026-09-03T16:12:00Z',
    requestHeadersMasked: {
      'Authorization': 'Bearer kp_test_••••••••••••••••••••••••3829fa01',
    },
    requestBodyMasked: {
      amount: 2500000,
      currency: 'NGN',
      customer_email: 'buyer@example.ng',
      reference: 'ORD-2026-99042',
    },
    responseBodyMasked: {
      status: 'success',
      reference: 'ORD-2026-99042',
      virtual_account: '9928193820',
    },
    providerNode: 'Providus Bank NG',
  },
  {
    id: 'req_log_004',
    requestId: 'KP-REQ-992810a4',
    correlationId: 'corr_sahel_99213',
    appId: 'app_sand_88201',
    appName: 'Sahel Cross-Border Mobile Hub (Sandbox)',
    environment: 'SANDBOX',
    method: 'POST',
    endpoint: '/v1/transfers/cross-border',
    statusCode: 422,
    latencyMs: 62,
    ipAddress: '160.154.20.5',
    country: 'NE',
    timestamp: '2026-09-03T16:05:00Z',
    requestHeadersMasked: {
      'Authorization': 'Bearer kp_test_••••••••••••••••••••••••3829fa01',
    },
    requestBodyMasked: {
      amount: -500,
      currency: 'NGN',
    },
    responseBodyMasked: {
      status: 'error',
      code: 'INVALID_AMOUNT',
      message: 'Amount must be an integer >= 100 in minor currency units.',
    },
    errorMessage: 'INVALID_AMOUNT: Negative minor currency units rejected.',
  },
  {
    id: 'req_log_005',
    requestId: 'KP-REQ-992810a5',
    correlationId: 'corr_sahel_99214',
    appId: 'app_sand_88201',
    appName: 'Sahel Cross-Border Mobile Hub (Sandbox)',
    environment: 'SANDBOX',
    method: 'GET',
    endpoint: '/v1/fx/corridor-rates',
    statusCode: 200,
    latencyMs: 38,
    ipAddress: '197.210.84.12',
    country: 'NG',
    timestamp: '2026-09-03T16:00:00Z',
    requestHeadersMasked: {
      'Authorization': 'Bearer kp_test_••••••••••••••••••••••••3829fa01',
    },
    responseBodyMasked: {
      status: 'success',
      corridor: 'NGN_XOF',
      rate: 0.43,
    },
  },
];

// 10. Error Analytics Summary
export const initialErrorAnalytics: ErrorAnalyticsSummary[] = [
  {
    errorCode: 'INVALID_AMOUNT',
    count: 312,
    percentage: 42.5,
    endpoint: '/v1/merchant/checkout',
    method: 'POST',
    category: 'VALIDATION',
    lastSeen: '10 mins ago',
    recommendedFix: 'Pass amounts as whole minor units (e.g. ₦1,000.00 = 100000 kobo). Do not include floating point decimals.',
  },
  {
    errorCode: 'DUPLICATE_IDEMPOTENCY_KEY',
    count: 184,
    percentage: 25.1,
    endpoint: '/v1/transfers/cross-border',
    method: 'POST',
    category: 'LEDGER',
    lastSeen: '18 mins ago',
    recommendedFix: 'Do not re-issue the same Idempotency-Key with different payload parameters. Use GET verify instead.',
  },
  {
    errorCode: 'RATE_LOCK_EXPIRED',
    count: 112,
    percentage: 15.3,
    endpoint: '/v1/transfers/cross-border',
    method: 'POST',
    category: 'PROVIDER',
    lastSeen: '45 mins ago',
    recommendedFix: 'Execute transfer within 60 seconds of calling /v1/fx/quote, or omit quote ID to use real-time spot lock.',
  },
  {
    errorCode: 'UNAUTHORIZED_SCOPE',
    count: 82,
    percentage: 11.2,
    endpoint: '/v2/nip-gateway/outward',
    method: 'POST',
    category: 'AUTH',
    lastSeen: '1 hour ago',
    recommendedFix: 'Ensure your API key has the transfers:write permission scope enabled in Developer Credentials.',
  },
  {
    errorCode: 'RATE_LIMIT_EXCEEDED',
    count: 43,
    percentage: 5.9,
    endpoint: '/v1/fx/corridor-rates',
    method: 'GET',
    category: 'RATE_LIMIT',
    lastSeen: '2 hours ago',
    recommendedFix: 'Cache corridor rates for at least 5 seconds locally instead of polling on every render cycle.',
  },
];

// 11. Rate Limits & Quotas
export const initialRateLimits: RateLimitQuota[] = [
  { category: 'payments', currentRpm: 48, maxRpm: 600, requestsToday: 18450, quotaToday: 100000, burstLimit: 900, throttleCountToday: 0 },
  { category: 'wallets', currentRpm: 12, maxRpm: 1200, requestsToday: 8210, quotaToday: 200000, burstLimit: 1500, throttleCountToday: 0 },
  { category: 'merchant', currentRpm: 32, maxRpm: 600, requestsToday: 12400, quotaToday: 100000, burstLimit: 800, throttleCountToday: 0 },
  { category: 'agency', currentRpm: 20, maxRpm: 300, requestsToday: 6500, quotaToday: 50000, burstLimit: 450, throttleCountToday: 0 },
  { category: 'fx_cross_border', currentRpm: 92, maxRpm: 1200, requestsToday: 42100, quotaToday: 200000, burstLimit: 1500, throttleCountToday: 0 },
  { category: 'kyc', currentRpm: 6, maxRpm: 120, requestsToday: 1840, quotaToday: 20000, burstLimit: 180, throttleCountToday: 0 },
  { category: 'bills', currentRpm: 14, maxRpm: 300, requestsToday: 4120, quotaToday: 50000, burstLimit: 400, throttleCountToday: 0 },
];

// 12. System Status Nodes
export const initialStatusNodes: SystemStatusNode[] = [
  {
    id: 'node_providus_ng',
    name: 'Providus Bank Nigeria NIP Banking Node',
    category: 'BANKING_NODE',
    jurisdiction: 'NG',
    status: 'OPERATIONAL',
    uptime90d: 99.94,
    latencyMs: 142,
    lastChecked: '30 seconds ago',
    providerName: 'Providus Bank Plc (Nigeria)',
  },
  {
    id: 'node_koris_ne',
    name: 'Coris Bank Niger Republic WAEMU Core Node',
    category: 'BANKING_NODE',
    jurisdiction: 'NE',
    status: 'OPERATIONAL',
    uptime90d: 99.88,
    latencyMs: 188,
    lastChecked: '45 seconds ago',
    providerName: 'Coris Bank International (Niger Republic)',
  },
  {
    id: 'node_api_gateway',
    name: 'KoriePay Edge API Gateway',
    category: 'API_GATEWAY',
    jurisdiction: 'GLOBAL',
    status: 'OPERATIONAL',
    uptime90d: 99.99,
    latencyMs: 24,
    lastChecked: '10 seconds ago',
  },
  {
    id: 'node_sandbox_engine',
    name: 'Developer Sandbox Simulation Engine',
    category: 'SANDBOX_ENGINE',
    jurisdiction: 'GLOBAL',
    status: 'OPERATIONAL',
    uptime90d: 99.95,
    latencyMs: 35,
    lastChecked: '15 seconds ago',
  },
  {
    id: 'node_webhook_dispatcher',
    name: 'HMAC Webhook Event Dispatcher & Ingest',
    category: 'WEBHOOK_DISPATCHER',
    jurisdiction: 'GLOBAL',
    status: 'OPERATIONAL',
    uptime90d: 99.92,
    latencyMs: 58,
    lastChecked: '20 seconds ago',
  },
  {
    id: 'node_kyc_orchestrator',
    name: 'Biometric & Identity Orchestrator (NIMC/NIBSS/NIF)',
    category: 'KYC_ORCHESTRATOR',
    jurisdiction: 'GLOBAL',
    status: 'OPERATIONAL',
    uptime90d: 99.72,
    latencyMs: 310,
    lastChecked: '1 min ago',
  },
];

// 13. Incidents
export const initialIncidents: PlatformIncident[] = [
  {
    id: 'inc_20260901_01',
    title: 'Intermittent NIBSS NIP Settlement Latency in Nigeria Corridor',
    severity: 'MINOR',
    status: 'RESOLVED',
    affectedNodes: ['Providus Bank Nigeria NIP Banking Node'],
    affectedEndpoints: ['/v2/nip-gateway/outward'],
    impactSummary: 'Intermittent outward NIP settlement delays up to 12 seconds during NIBSS upstream window.',
    startedAt: '2026-09-01T14:10:00Z',
    resolvedAt: '2026-09-01T15:25:00Z',
    updates: [
      { timestamp: '2026-09-01T15:25:00Z', status: 'RESOLVED', message: 'NIBSS switch latency normalized. All queued retry payouts completed.' },
      { timestamp: '2026-09-01T14:35:00Z', status: 'IDENTIFIED', message: 'Upstream NIBSS clearing gateway throttling outward packets.' },
      { timestamp: '2026-09-01T14:10:00Z', status: 'INVESTIGATING', message: 'Engineering alerted to elevated round-trip times on Providus NIP node.' },
    ],
  },
];

// 14. SDK Packages
export const initialSdks: SdkPackage[] = [
  {
    id: 'sdk_node',
    language: 'Node.js / TypeScript',
    name: '@koriepay/node-sdk',
    version: '1.4.2',
    packageManager: 'npm',
    installCommand: 'npm install @koriepay/node-sdk',
    repositoryUrl: 'https://github.com/koriepay/koriepay-node-sdk',
    docsUrl: '/developers/sdks#node',
    status: 'GA',
    releaseDate: '2026-08-20',
    features: ['TypeScript strict types', 'Automatic Idempotency headers', 'Webhook HMAC signature verification', 'Bilateral NGN/XOF helpers'],
  },
  {
    id: 'sdk_python',
    language: 'Python',
    name: 'koriepay-python',
    version: '1.3.1',
    packageManager: 'pip',
    installCommand: 'pip install koriepay',
    repositoryUrl: 'https://github.com/koriepay/koriepay-python',
    docsUrl: '/developers/sdks#python',
    status: 'GA',
    releaseDate: '2026-08-10',
    features: ['Asyncio support', 'Pydantic data models', 'Webhook verification helper', 'Providus NIP client'],
  },
  {
    id: 'sdk_php',
    language: 'PHP',
    name: 'koriepay/koriepay-php',
    version: '1.2.0',
    packageManager: 'composer',
    installCommand: 'composer require koriepay/koriepay-php',
    repositoryUrl: 'https://github.com/koriepay/koriepay-php',
    docsUrl: '/developers/sdks#php',
    status: 'GA',
    releaseDate: '2026-07-28',
    features: ['PSR-18 HTTP client', 'Laravel & Symfony integration', 'Webhook middleware', 'Dynamic checkout generator'],
  },
  {
    id: 'sdk_go',
    language: 'Go',
    name: 'github.com/koriepay/koriepay-go',
    version: '1.1.0',
    packageManager: 'go get',
    installCommand: 'go get github.com/koriepay/koriepay-go',
    repositoryUrl: 'https://github.com/koriepay/koriepay-go',
    docsUrl: '/developers/sdks#go',
    status: 'GA',
    releaseDate: '2026-07-15',
    features: ['Context support', 'Zero-allocation JSON parsing', 'Goroutine-safe client pool', 'Cross-border rate lock manager'],
  },
  {
    id: 'sdk_java',
    language: 'Java / Kotlin',
    name: 'com.koriepay:koriepay-java',
    version: '1.2.4',
    packageManager: 'maven',
    installCommand: '<dependency>\n  <groupId>com.koriepay</groupId>\n  <artifactId>koriepay-java</artifactId>\n  <version>1.2.4</version>\n</dependency>',
    repositoryUrl: 'https://github.com/koriepay/koriepay-java',
    docsUrl: '/developers/sdks#java',
    status: 'GA',
    releaseDate: '2026-06-30',
    features: ['Spring Boot Starter', 'Android POS terminal compatible', 'OkHttp client integration', 'EMV QR parser'],
  },
  {
    id: 'sdk_dotnet',
    language: 'C# / .NET',
    name: 'KoriePay.Sdk',
    version: '1.0.8',
    packageManager: 'nuget',
    installCommand: 'dotnet add package KoriePay.Sdk',
    repositoryUrl: 'https://github.com/koriepay/koriepay-dotnet',
    docsUrl: '/developers/sdks#dotnet',
    status: 'GA',
    releaseDate: '2026-06-12',
    features: ['.NET 8 & 9 support', 'Dependency injection extensions', 'Webhook handler middleware', 'Strongly typed DTOs'],
  },
];

// 15. Integration Checklist & Production Readiness
export const initialIntegrationChecklist: IntegrationChecklistItem[] = [
  {
    id: 'chk_01',
    title: 'Secret Key Authentication Configured',
    category: 'AUTH',
    status: 'COMPLETED',
    description: 'Sandbox API keys successfully authenticated via HTTP Bearer token headers.',
    verificationEvidence: 'HTTP 200 returned on /v1/wallets/create test ping.',
  },
  {
    id: 'chk_02',
    title: 'Idempotency-Key Enforced on Financial Routes',
    category: 'INTEGRATION',
    status: 'COMPLETED',
    description: 'Every POST request to /v1/transfers/cross-border and /v1/merchant/checkout transmits a valid UUID v4 Idempotency-Key.',
    verificationEvidence: 'Tested 2 identical Idempotency-Key dispatches; returned 409 idempotency lock prevention.',
  },
  {
    id: 'chk_03',
    title: 'Webhook HMAC-SHA256 Signature Verification',
    category: 'WEBHOOK',
    status: 'COMPLETED',
    description: 'Endpoint validates X-KoriePay-Signature header using registered signing secret before processing payloads.',
    verificationEvidence: 'Dispatched test ping to https://webhook.saheltech.io/sandbox/koriepay-events; returned HTTP 200.',
  },
  {
    id: 'chk_04',
    title: 'Standard Error & 4xx/5xx Exception Handling',
    category: 'ERROR_HANDLING',
    status: 'COMPLETED',
    description: 'System gracefully catches and logs structured KoriePay error codes (e.g. INSUFFICIENT_FUNDS, INVALID_AMOUNT).',
    verificationEvidence: 'Logged 422 INVALID_AMOUNT response simulation successfully.',
  },
  {
    id: 'chk_05',
    title: 'IP Address Whitelisting Configured',
    category: 'SECURITY',
    status: 'COMPLETED',
    description: 'Production traffic is restricted to verified merchant server egress IP addresses.',
    verificationEvidence: 'Whitelisted IPs: 197.210.84.12, 197.210.84.13, 160.154.20.10.',
  },
  {
    id: 'chk_06',
    title: 'Daily Settlement & Ledger Reconciliation Job',
    category: 'RECONCILIATION',
    status: 'COMPLETED',
    description: 'Nightly batch query to /v1/payments/{ref}/verify to balance ERP records with Providus & Coris bank settlements.',
    verificationEvidence: 'Automated 23:59:00 UTC reconciliation script verified.',
  },
];

// 16. Production Access Request
export const initialProductionRequest: ProductionAccessRequest = {
  id: 'prod_req_99210',
  orgId: 'org_kor_99182',
  orgName: 'Sahel Global Technologies Ltd',
  applicantEmail: 'i.abubakar@saheltech.io',
  requestedAt: '2026-08-28T10:00:00Z',
  status: 'APPROVED',
  readinessScore: 100,
  complianceKybStatus: 'VERIFIED',
  settlementAccountVerified: true,
  settlementBank: 'Providus Bank Nigeria',
  settlementNuban: '0098192039',
  reviewerNotes: 'Verified CAC corporate registration, Providus Bank settlement NUBAN, and successful end-to-end sandbox simulation test.',
  reviewedBy: 'Compliance Desk (Amina Bello)',
  reviewedAt: '2026-09-01T08:30:00Z',
  checklistResults: {
    authentication: true,
    sandboxSuccess: true,
    webhookSignatureTested: true,
    idempotencyEnforced: true,
    errorHandlingVerified: true,
    ipWhitelistConfigured: true,
  },
};

// 17. Developer Support Cases
export const initialSupportCases: DeveloperSupportCase[] = [
  {
    id: 'case_dev_01',
    ticketNumber: 'DEV-CASE-99201',
    subject: 'Cross-Border corridor rate lock timeout clarification',
    category: 'INTEGRATION_GUIDANCE',
    priority: 'MEDIUM',
    status: 'RESOLVED',
    applicationId: 'app_sand_88201',
    environment: 'SANDBOX',
    endpoint: 'POST /v1/transfers/cross-border',
    requestId: 'KP-REQ-992810a4',
    errorCode: 'RATE_LOCK_EXPIRED',
    description: 'We noticed rate locks expire after 60 seconds. Can we configure 120 seconds for slow consumer confirmation flows?',
    createdAt: '2026-09-02T09:00:00Z',
    updatedAt: '2026-09-02T11:30:00Z',
    messagesCount: 3,
  },
  {
    id: 'case_dev_02',
    ticketNumber: 'DEV-CASE-99202',
    subject: 'Providus Bank virtual account callback delay in sandbox test',
    category: 'WEBHOOK_FAILURE',
    priority: 'LOW',
    status: 'IN_PROGRESS',
    applicationId: 'app_sand_88201',
    environment: 'SANDBOX',
    endpoint: 'POST /v1/merchant/accounts/virtual',
    requestId: 'KP-REQ-992810a3',
    description: 'Sandbox webhook ping for virtual account simulated payment took 15 seconds to dispatch.',
    createdAt: '2026-09-03T14:00:00Z',
    updatedAt: '2026-09-03T15:20:00Z',
    messagesCount: 2,
  },
];

// 18. Developer Audit Logs
export const initialDeveloperAuditLogs: DeveloperAuditLog[] = [
  {
    id: 'daudit_001',
    actorEmail: 'i.abubakar@saheltech.io',
    actorRole: 'OWNER',
    action: 'PRODUCTION_KEY_GENERATED',
    resourceType: 'CREDENTIAL',
    resourceId: 'cred_prod_01',
    details: 'Generated live secret key pk_live_992817... for production application.',
    ipAddress: '197.210.84.12',
    timestamp: '2026-09-01T09:30:00Z',
    environment: 'PRODUCTION',
  },
  {
    id: 'daudit_002',
    actorEmail: 'm.seydou@saheltech.io',
    actorRole: 'DEVELOPER',
    action: 'WEBHOOK_ENDPOINT_UPDATED',
    resourceType: 'WEBHOOK',
    resourceId: 'whk_sand_01',
    details: 'Subscribed to events: payment.successful, payment.failed, transfer.successful, transfer.failed.',
    ipAddress: '160.154.20.5',
    timestamp: '2026-09-02T10:15:00Z',
    environment: 'SANDBOX',
  },
  {
    id: 'daudit_003',
    actorEmail: 'amina.bello@saheltech.io',
    actorRole: 'ADMIN',
    action: 'IP_WHITELIST_MODIFIED',
    resourceType: 'APPLICATION',
    resourceId: 'app_prod_99402',
    details: 'Added server egress IP 160.154.20.10 to production application whitelist.',
    ipAddress: '197.210.84.13',
    timestamp: '2026-09-02T14:40:00Z',
    environment: 'PRODUCTION',
  },
];
