import {
  SupportOfficer,
  SupportTicket,
  Customer360Context,
  TransactionInvestigationContext,
  SupportPlaybook,
  KnowledgeArticle,
  SupportIncident,
  AutomationRule,
  AutomationExecutionLog,
  QaReview,
  TrainingModule,
  StaffCapacityMetric,
  SupportHealthScore,
  SupportAuditEntry,
} from '@/types/support';

// ============================================================================
// 1. SUPPORT OFFICERS ROSTER
// ============================================================================
export const MOCK_SUPPORT_OFFICERS: SupportOfficer[] = [
  {
    id: 'OFF-SUP-01',
    fullName: 'Zainab Abubakar',
    email: 'zainab.support@koriepay.internal',
    role: 'TIER_1_JUNIOR',
    tier: 'TIER_1_JUNIOR',
    jurisdiction: 'NG',
    languages: ['en', 'ha'],
    activeTicketCount: 6,
    maxCapacity: 12,
    status: 'ONLINE',
    qaScore: 94.5,
    avatarUrl: '/avatars/zainab.jpg',
    skills: ['Transfers', 'Agent POS', 'Airtime/Data', 'Hausa Support'],
    joinedDate: '2026-06-15',
  },
  {
    id: 'OFF-SUP-02',
    fullName: 'Abdoul-Razak Souley',
    email: 'abdoul.support@koriepay.internal',
    role: 'TIER_1_JUNIOR',
    tier: 'TIER_1_JUNIOR',
    jurisdiction: 'NE',
    languages: ['fr', 'ha'],
    activeTicketCount: 5,
    maxCapacity: 12,
    status: 'ONLINE',
    qaScore: 92.0,
    avatarUrl: '/avatars/abdoul.jpg',
    skills: ['XOF Transfers', 'Coris Node', 'Merchant Payouts', 'French Support'],
    joinedDate: '2026-07-01',
  },
  {
    id: 'OFF-SUP-03',
    fullName: 'Chidinma Eze',
    email: 'chidinma.senior@koriepay.internal',
    role: 'TIER_2_SENIOR',
    tier: 'TIER_2_SENIOR',
    jurisdiction: 'NG',
    languages: ['en'],
    activeTicketCount: 4,
    maxCapacity: 8,
    status: 'ONLINE',
    qaScore: 98.2,
    avatarUrl: '/avatars/chidinma.jpg',
    skills: ['Complex Disputes', 'Reconciliation', 'High-Value Escalations'],
    joinedDate: '2025-10-10',
  },
  {
    id: 'OFF-SUP-04',
    fullName: 'Haruna Dan-Borno',
    email: 'haruna.supervisor@koriepay.internal',
    role: 'SUPPORT_SUPERVISOR',
    tier: 'MANAGEMENT',
    jurisdiction: 'CROSS_BORDER',
    languages: ['en', 'ha', 'fr'],
    activeTicketCount: 2,
    maxCapacity: 6,
    status: 'ONLINE',
    qaScore: 99.1,
    avatarUrl: '/avatars/haruna.jpg',
    skills: ['Queue Management', 'Incident Leadership', 'QA Scoring', 'Playbook Authoring'],
    joinedDate: '2025-03-01',
  },
  {
    id: 'OFF-SUP-05',
    fullName: 'Femi Alabi',
    email: 'femi.finance@koriepay.internal',
    role: 'TIER_3_FINANCE',
    tier: 'TIER_3_SPECIALIST',
    jurisdiction: 'NG',
    languages: ['en'],
    activeTicketCount: 3,
    maxCapacity: 10,
    status: 'BUSY',
    qaScore: 97.4,
    skills: ['Ledger Reconciliation', 'Settlement Adjustment', 'Refund Verification'],
    joinedDate: '2025-06-20',
  },
  {
    id: 'OFF-SUP-06',
    fullName: 'Amina Bello, CAMS',
    email: 'amina.compliance@koriepay.internal',
    role: 'TIER_3_COMPLIANCE',
    tier: 'TIER_3_SPECIALIST',
    jurisdiction: 'CROSS_BORDER',
    languages: ['en', 'ha'],
    activeTicketCount: 2,
    maxCapacity: 8,
    status: 'ONLINE',
    qaScore: 99.8,
    skills: ['KYC/KYB Clearance', 'AML Holds', 'Sanctions Review', 'Court Directives'],
    joinedDate: '2025-01-15',
  },
  {
    id: 'OFF-SUP-07',
    fullName: 'Tariq Al-Mansoor',
    email: 'tariq.techops@koriepay.internal',
    role: 'TIER_3_TECH_OPS',
    tier: 'TIER_3_SPECIALIST',
    jurisdiction: 'CROSS_BORDER',
    languages: ['en'],
    activeTicketCount: 4,
    maxCapacity: 10,
    status: 'ONLINE',
    qaScore: 98.0,
    skills: ['Webhook Replay', 'API Latency', 'Providus & Coris Rail Diagnostics'],
    joinedDate: '2025-04-12',
  },
];

// ============================================================================
// 2. SUPPORT TICKETS REGISTRY
// ============================================================================
export const MOCK_SUPPORT_TICKETS: SupportTicket[] = [
  {
    id: 'TCK-2026-10491',
    ticketNumber: 'KP-SUP-10491',
    subject: 'Transfer Debited from Wallet but Not Received by GTBank Beneficiary',
    description: 'I sent ₦45,000 to my supplier account via NIP transfer 2 hours ago. My wallet was debited immediately, but the recipient has not received the alert or funds.',
    category: 'PENDING_TRANSACTION',
    priority: 'HIGH',
    status: 'IN_PROGRESS',
    customerType: 'CUSTOMER',
    customerId: 'CUST-NG-88912',
    customerName: 'Ibrahim Danladi',
    customerEmail: 'i.danladi@kanotrades.com',
    customerPhone: '+234 803 123 4567',
    jurisdiction: 'NG',
    channel: 'IN_APP',
    language: 'en',
    assignedOfficerId: 'OFF-SUP-01',
    assignedOfficerName: 'Zainab Abubakar',
    tierAssigned: 'TIER_1_JUNIOR',
    relatedTransactionId: 'TX-NG-2026-99201',
    createdAt: '2026-09-03T11:15:00Z',
    updatedAt: '2026-09-03T11:45:00Z',
    firstResponseDueAt: '2026-09-03T11:45:00Z',
    resolutionDueAt: '2026-09-03T15:15:00Z',
    firstRespondedAt: '2026-09-03T11:22:00Z',
    slaStatus: 'HEALTHY',
    tags: ['NIP Transfer', 'Providus Outbound', 'GTBank', 'Pending Status'],
    sentiment: 'FRUSTRATED',
    messages: [
      {
        id: 'MSG-001',
        ticketId: 'TCK-2026-10491',
        senderType: 'CUSTOMER',
        senderId: 'CUST-NG-88912',
        senderName: 'Ibrahim Danladi',
        content: 'Good day, please help me check this transfer of ₦45,000. My account was debited at 11:10 AM, reference KP-NIP-99201, but the beneficiary has not received credit.',
        isInternalNote: false,
        timestamp: '2026-09-03T11:15:00Z',
      },
      {
        id: 'MSG-002',
        ticketId: 'TCK-2026-10491',
        senderType: 'SYSTEM',
        senderId: 'SYSTEM-AUTO',
        senderName: 'KoriePay Telemetry Engine',
        content: 'System detected NIP transfer transaction TX-NG-2026-99201. Status: PENDING_BENEFICIARY_ACK. Provider: Providus Bank Node. Auto-attached Transaction Investigation timeline.',
        isInternalNote: true,
        timestamp: '2026-09-03T11:15:05Z',
      },
      {
        id: 'MSG-003',
        ticketId: 'TCK-2026-10491',
        senderType: 'AGENT',
        senderId: 'OFF-SUP-01',
        senderName: 'Zainab Abubakar',
        content: 'Hello Mr. Danladi, thank you for contacting KoriePay Support. I have retrieved transaction KP-NIP-99201. Our banking rail has dispatched the funds and we are currently awaiting the final settlement acknowledgment from GTBank. If the receiving bank does not complete processing within 1 hour, our automated reconciliation will reverse the funds back to your wallet.',
        isInternalNote: false,
        timestamp: '2026-09-03T11:22:00Z',
        macroUsed: 'MACRO_NIP_PENDING_ACK',
      },
      {
        id: 'MSG-004',
        ticketId: 'TCK-2026-10491',
        senderType: 'AGENT',
        senderId: 'OFF-SUP-01',
        senderName: 'Zainab Abubakar',
        content: 'Verified NIBSS session ID 99920126090311100012. Destination GTBank switch is experiencing transient latency. Escalation not required; auto-reversal scheduled if pending past 12:15 PM.',
        isInternalNote: true,
        timestamp: '2026-09-03T11:25:00Z',
      },
    ],
  },
  {
    id: 'TCK-2026-10492',
    ticketNumber: 'KP-SUP-10492',
    subject: 'Problème de Solde Float sur Terminal POS à Niamey Grand Marché',
    description: 'Le terminal POS refuse le cashout client en indiquant "Solde Insuffisant" alors que le rechargement Coris Bank de 500,000 XOF a été effectué ce matin.',
    category: 'AGENT_FLOAT',
    priority: 'URGENT',
    status: 'IN_PROGRESS',
    customerType: 'AGENT',
    customerId: 'AGT-NE-2009',
    customerName: 'Niamey Grand Marché Kiosk (Souley Amadou)',
    customerPhone: '+227 90 44 88 12',
    jurisdiction: 'NE',
    channel: 'AGENT_PORTAL',
    language: 'fr',
    assignedOfficerId: 'OFF-SUP-02',
    assignedOfficerName: 'Abdoul-Razak Souley',
    tierAssigned: 'TIER_1_JUNIOR',
    relatedTransactionId: 'TX-NE-2026-44019',
    createdAt: '2026-09-03T10:30:00Z',
    updatedAt: '2026-09-03T11:30:00Z',
    firstResponseDueAt: '2026-09-03T10:45:00Z',
    resolutionDueAt: '2026-09-03T12:30:00Z',
    firstRespondedAt: '2026-09-03T10:38:00Z',
    slaStatus: 'HEALTHY',
    tags: ['Coris Bank Float', 'POS Agent', 'Niamey', 'XOF Wallet'],
    sentiment: 'FRUSTRATED',
    messages: [
      {
        id: 'MSG-010',
        ticketId: 'TCK-2026-10492',
        senderType: 'CUSTOMER',
        senderId: 'AGT-NE-2009',
        senderName: 'Souley Amadou',
        content: 'Bonjour le support, mon terminal POS #02 affiche une erreur de float épuisé alors que j\'ai viré 500 000 FCFA depuis Coris Bank à 09h00. Les clients font la queue.',
        isInternalNote: false,
        timestamp: '2026-09-03T10:30:00Z',
      },
      {
        id: 'MSG-011',
        ticketId: 'TCK-2026-10492',
        senderType: 'AGENT',
        senderId: 'OFF-SUP-02',
        senderName: 'Abdoul-Razak Souley',
        content: 'Bonjour M. Amadou, nous traitons votre dossier en priorité. Le virement Coris Bank de 500 000 FCFA a bien été identifié sous la référence KB-NE-88491. Le rafraîchissement du solde float sur votre terminal a été synchronisé.',
        isInternalNote: false,
        timestamp: '2026-09-03T10:38:00Z',
      },
    ],
  },
  {
    id: 'TCK-2026-10493',
    ticketNumber: 'KP-SUP-10493',
    subject: 'Merchant Daily Settlement Payout Delay for Cross-Border Grain Sales',
    description: 'Our automated T+1 settlement of ₦14,200,000 for Kano-Maradi deliveries from yesterday has not hit our Providus corporate account.',
    category: 'MERCHANT_SETTLEMENT',
    priority: 'HIGH',
    status: 'ESCALATED',
    customerType: 'MERCHANT',
    customerId: 'MCH-NG-1004',
    customerName: 'Dawanau Grain Consolidated Enterprises Ltd',
    customerEmail: 'finance@dawanaugrain.ng',
    customerPhone: '+234 803 991 2288',
    jurisdiction: 'CROSS_BORDER',
    channel: 'MERCHANT_PORTAL',
    language: 'en',
    assignedOfficerId: 'OFF-SUP-05',
    assignedOfficerName: 'Femi Alabi (Finance Ops)',
    tierAssigned: 'TIER_3_SPECIALIST',
    createdAt: '2026-09-03T09:00:00Z',
    updatedAt: '2026-09-03T11:50:00Z',
    firstResponseDueAt: '2026-09-03T09:30:00Z',
    resolutionDueAt: '2026-09-03T13:00:00Z',
    firstRespondedAt: '2026-09-03T09:18:00Z',
    slaStatus: 'HEALTHY',
    tags: ['Merchant Settlement', 'High Value', 'Finance Escalation', 'Cross-Border'],
    sentiment: 'NEUTRAL',
    messages: [
      {
        id: 'MSG-020',
        ticketId: 'TCK-2026-10493',
        senderType: 'CUSTOMER',
        senderId: 'MCH-NG-1004',
        senderName: 'Alhaji Sani Dawanau',
        content: 'Please verify the status of our merchant batch settlement #SET-2026-0902-88. Value is ₦14.2M. Needs urgent clearance for grain procurement trucks.',
        isInternalNote: false,
        timestamp: '2026-09-03T09:00:00Z',
      },
      {
        id: 'MSG-021',
        ticketId: 'TCK-2026-10493',
        senderType: 'AGENT',
        senderId: 'OFF-SUP-03',
        senderName: 'Chidinma Eze',
        content: 'Escalated to Finance Operations for manual batch release confirmation. Transaction amount requires dual-authorized Treasury batch release.',
        isInternalNote: true,
        timestamp: '2026-09-03T09:20:00Z',
      },
    ],
  },
  {
    id: 'TCK-2026-10494',
    ticketNumber: 'KP-SUP-10494',
    subject: 'Yadda zan canza lambar wayata da aka yi rajista (Phone Number Update)',
    description: 'Ina so in canza lambar wayar asusun KoriePay dina saboda tsohuwar lambar ta bace. Yaya zan yi?',
    category: 'LOGIN_ACCESS',
    priority: 'NORMAL',
    status: 'TRIAGED',
    customerType: 'CUSTOMER',
    customerId: 'CUST-NG-99044',
    customerName: 'Fatima Sanusi',
    customerPhone: '+234 814 555 9901',
    jurisdiction: 'NG',
    channel: 'WHATSAPP',
    language: 'ha',
    assignedOfficerId: 'OFF-SUP-01',
    assignedOfficerName: 'Zainab Abubakar',
    tierAssigned: 'TIER_1_JUNIOR',
    createdAt: '2026-09-03T11:30:00Z',
    updatedAt: '2026-09-03T11:40:00Z',
    firstResponseDueAt: '2026-09-03T13:30:00Z',
    resolutionDueAt: '2026-09-04T11:30:00Z',
    slaStatus: 'HEALTHY',
    tags: ['Hausa', 'Security', 'Phone Change', 'NIN Verification'],
    sentiment: 'NEUTRAL',
    messages: [
      {
        id: 'MSG-030',
        ticketId: 'TCK-2026-10494',
        senderType: 'CUSTOMER',
        senderId: 'CUST-NG-99044',
        senderName: 'Fatima Sanusi',
        content: 'Salam alaikum, ina neman taimako don canza lambar waya a kan asusuna na KoriePay. Na gode.',
        isInternalNote: false,
        timestamp: '2026-09-03T11:30:00Z',
      },
    ],
  },
  {
    id: 'TCK-2026-10495',
    ticketNumber: 'KP-SUP-10495',
    subject: 'Automated Dispute: ATM Cash Dispense Error at Wuse Zone 4',
    description: 'Debit card cash withdrawal attempt of ₦20,000 at FirstBank ATM failed with error 91 (Issuer Inoperative), but KoriePay card wallet was debited.',
    category: 'CARD',
    priority: 'HIGH',
    status: 'NEW',
    customerType: 'CUSTOMER',
    customerId: 'CUST-NG-44102',
    customerName: 'Chukwuemeka Okoye',
    customerPhone: '+234 802 334 9901',
    jurisdiction: 'NG',
    channel: 'IN_APP',
    language: 'en',
    tierAssigned: 'TIER_0_AUTOMATION',
    createdAt: '2026-09-03T11:50:00Z',
    updatedAt: '2026-09-03T11:50:00Z',
    firstResponseDueAt: '2026-09-03T12:20:00Z',
    resolutionDueAt: '2026-09-03T15:50:00Z',
    slaStatus: 'HEALTHY',
    tags: ['Card ATM', 'Interswitch Error 91', 'Auto-Dispute', 'Reversal Queue'],
    sentiment: 'FRUSTRATED',
    messages: [
      {
        id: 'MSG-040',
        ticketId: 'TCK-2026-10495',
        senderType: 'CUSTOMER',
        senderId: 'CUST-NG-44102',
        senderName: 'Chukwuemeka Okoye',
        content: 'I tried to withdraw ₦20,000 at FirstBank ATM in Wuse Zone 4. ATM did not give cash but debited my card.',
        isInternalNote: false,
        timestamp: '2026-09-03T11:50:00Z',
      },
      {
        id: 'MSG-041',
        ticketId: 'TCK-2026-10495',
        senderType: 'AUTOMATION',
        senderId: 'RULE-CARD-DISPENSE-01',
        senderName: 'Automated ATM Dispute Bot',
        content: 'Interswitch switch message RC91 detected. Transaction TX-CARD-8819 marked as unfulfilled. Auto-credit scheduled in 24 hours per CBN Dispute Guidelines.',
        isInternalNote: true,
        timestamp: '2026-09-03T11:50:10Z',
      },
    ],
  },
];

// ============================================================================
// 3. CUSTOMER 360° CONTEXT MAPPINGS
// ============================================================================
export const MOCK_CUSTOMER_360_MAP: Record<string, Customer360Context> = {
  'CUST-NG-88912': {
    customerId: 'CUST-NG-88912',
    fullName: 'Ibrahim Danladi',
    emailMasked: 'i.d*****@kanotrades.com',
    phoneMasked: '+234 803 *** 4567',
    country: 'NG',
    preferredLanguage: 'en',
    kycTier: 'TIER_3',
    accountStatus: 'ACTIVE',
    walletBalanceMasked: '₦1,842,500.00',
    currency: 'NGN',
    totalTransactionsCount: 148,
    failedTransactionsCount: 3,
    registrationDate: '2025-08-14',
    activeTicketsCount: 1,
    riskLevel: 'LOW',
    securityEvents: [
      { event: 'Biometric Login', device: 'Samsung Galaxy S24', ipMasked: '102.89.***.***', timestamp: '2026-09-03 11:10:00' },
      { event: 'PIN Verification Passed', device: 'Samsung Galaxy S24', ipMasked: '102.89.***.***', timestamp: '2026-09-03 11:10:45' },
    ],
  },
  'AGT-NE-2009': {
    customerId: 'AGT-NE-2009',
    fullName: 'Niamey Grand Marché Kiosk (Souley Amadou)',
    emailMasked: 's.ama****@gmail.com',
    phoneMasked: '+227 90 *** 8812',
    country: 'NE',
    preferredLanguage: 'fr',
    kycTier: 'TIER_3',
    accountStatus: 'ACTIVE',
    walletBalanceMasked: '3,450,000 FCFA',
    currency: 'XOF',
    totalTransactionsCount: 1240,
    failedTransactionsCount: 14,
    registrationDate: '2025-03-20',
    activeTicketsCount: 1,
    riskLevel: 'LOW',
    securityEvents: [
      { event: 'POS Terminal Login (PAX A920)', device: 'PAX Terminal #02', ipMasked: '41.138.***.***', timestamp: '2026-09-03 08:30:00' },
    ],
  },
  'MCH-NG-1004': {
    customerId: 'MCH-NG-1004',
    fullName: 'Dawanau Grain Consolidated Enterprises Ltd',
    emailMasked: 'fin****@dawanaugrain.ng',
    phoneMasked: '+234 803 *** 2288',
    country: 'NG',
    preferredLanguage: 'en',
    kycTier: 'TIER_3',
    accountStatus: 'ACTIVE',
    walletBalanceMasked: '₦28,950,000.00',
    currency: 'NGN',
    totalTransactionsCount: 890,
    failedTransactionsCount: 4,
    registrationDate: '2025-02-10',
    activeTicketsCount: 1,
    riskLevel: 'LOW',
    securityEvents: [
      { event: 'Web Portal Corporate Login', device: 'Chrome on Mac OS X', ipMasked: '197.210.***.***', timestamp: '2026-09-03 08:45:00' },
    ],
  },
};

// ============================================================================
// 4. TRANSACTION INVESTIGATION CONTEXT MAPPINGS
// ============================================================================
export const MOCK_TRANSACTION_INVESTIGATION_MAP: Record<string, TransactionInvestigationContext> = {
  'TX-NG-2026-99201': {
    transactionId: 'TX-NG-2026-99201',
    reference: 'KP-NIP-99201-20260903',
    amount: 45000,
    currency: 'NGN',
    timestamp: '2026-09-03T11:10:22Z',
    status: 'PENDING',
    channel: 'NIP_OUTBOUND_TRANSFER',
    originEntity: 'Ibrahim Danladi (CUST-NG-88912)',
    destinationEntity: 'Al-Hassan Agro Supplies (GTBank 0123456789)',
    providerNode: 'Providus Bank NIP Clearing Rail',
    providerReference: 'PROV-NIP-998201940',
    webhookStatus: 'PENDING_ACK',
    ledgerPostingStatus: 'POSTED_BALANCED',
    canAutomateRefund: true,
    timeline: [
      { stage: 'Wallet Debit Initiated', timestamp: '11:10:22', status: 'PASS', details: '₦45,000 debited from ledger account #1001-88912' },
      { stage: 'Dispatch to Providus Rail', timestamp: '11:10:24', status: 'PASS', details: 'NIBSS Session ID generated: 99920126090311100012' },
      { stage: 'GTBank Switch Processing', timestamp: '11:10:26', status: 'WARN', details: 'GTBank switch response delayed past 15s standard window' },
      { stage: 'Automated Status Inquiries', timestamp: '11:20:00', status: 'WARN', details: 'TSQ inquiry returned status 09 (In Progress)' },
    ],
  },
  'TX-NE-2026-44019': {
    transactionId: 'TX-NE-2026-44019',
    reference: 'KP-KB-FLOAT-44019',
    amount: 500000,
    currency: 'XOF',
    timestamp: '2026-09-03T09:00:15Z',
    status: 'SUCCESSFUL',
    channel: 'KORIS_BANK_FLOAT_TOPUP',
    originEntity: 'Coris Bank Account #NE0192834',
    destinationEntity: 'Niamey Grand Marché Kiosk (AGT-NE-2009)',
    providerNode: 'Coris Bank Core NE',
    providerReference: 'KB-NE-8849102',
    webhookStatus: 'RECEIVED_CONFIRMED',
    ledgerPostingStatus: 'POSTED_BALANCED',
    canAutomateRefund: false,
    timeline: [
      { stage: 'Inbound Wire Verified', timestamp: '09:00:15', status: 'PASS', details: '500,000 XOF received via BCEAO STAR-UEMOA clearing' },
      { stage: 'Agent Wallet Credited', timestamp: '09:00:18', status: 'PASS', details: 'Float balance incremented to 3,450,000 XOF' },
      { stage: 'POS Cloud Sync Triggered', timestamp: '10:35:00', status: 'PASS', details: 'Manual push sent to PAX Terminal #02; terminal synced' },
    ],
  },
};

// ============================================================================
// 5. GUIDED STEP-BY-STEP PLAYBOOKS FOR JUNIOR OFFICERS
// ============================================================================
export const MOCK_SUPPORT_PLAYBOOKS: SupportPlaybook[] = [
  {
    id: 'PB-NIP-PENDING',
    title: 'Transfer Debited but Beneficiary Not Credited (NIP / Interswitch)',
    category: 'PENDING_TRANSACTION',
    targetTier: 'TIER_1_JUNIOR',
    estimatedMinutes: 3,
    requiredRole: 'TIER_1_JUNIOR',
    applicableJurisdictions: ['NG', 'CROSS_BORDER'],
    steps: [
      {
        stepNumber: 1,
        title: 'Verify Customer Identity & Session Context',
        instructions: 'Check that caller/chat matches authenticated Customer 360 profile. Ensure customer phone/email is verified.',
        checklistItems: ['Customer authenticated in app', 'No recent SIM-swap or takeover alert'],
        recommendedAction: 'Proceed to transaction lookup.',
      },
      {
        stepNumber: 2,
        title: 'Inspect Transaction Investigation Timeline',
        instructions: 'Open the Transaction Investigation panel on the right. Verify if NIBSS status code is 00 (Success), 09 (Pending), or 91/96 (Error).',
        checklistItems: ['Reference located on ledger', 'Debit status verified', 'Provider status verified'],
        recommendedAction: 'If status is 09, inform customer about standard receiving bank reconciliation window.',
        macroResponseKey: 'MACRO_NIP_PENDING_ACK',
      },
      {
        stepNumber: 3,
        title: 'Determine Resolution & Communication',
        instructions: 'If transaction is <1 hour old and status is 09, send Approved NIP Pending Template. Advise automated reversal occurs within 24h if unfulfilled.',
        checklistItems: ['Sent approved trilingual response', 'Customer reassured with exact NIBSS reference'],
        recommendedAction: 'Close ticket with resolution status or flag for auto-followup.',
        macroResponseKey: 'MACRO_NIP_PENDING_ACK',
      },
      {
        stepNumber: 4,
        title: 'Escalation Threshold',
        instructions: 'If transaction has been pending for >24 hours without reversal, click "Escalate to Finance Operations" with one click.',
        checklistItems: ['Escalated only if >24 hours'],
        recommendedAction: 'Escalate to Tier-3 Finance with NIBSS Session ID.',
      },
    ],
  },
  {
    id: 'PB-AGENT-FLOAT',
    title: 'POS Terminal Float Sync & Cashout Rejection Troubleshooting',
    category: 'AGENT_FLOAT',
    targetTier: 'TIER_1_JUNIOR',
    estimatedMinutes: 4,
    requiredRole: 'TIER_1_JUNIOR',
    applicableJurisdictions: ['NG', 'NE'],
    steps: [
      {
        stepNumber: 1,
        title: 'Check Agent Terminal Connection Status',
        instructions: 'Inspect the Agent POS telemetry feed to see if terminal is online on 4G/GPRS network and last heartbeat time.',
        checklistItems: ['Terminal serial confirmed', 'Agent float balance inspected'],
        recommendedAction: 'Check if topup inbound transfer has completed on ledger.',
      },
      {
        stepNumber: 2,
        title: 'Execute Cloud Float Refresh',
        instructions: 'Click the "Sync Float to Terminal" action button to trigger an MQTT push notification to the PAX/Sunmi device.',
        checklistItems: ['MQTT push confirmed', 'Agent requested to reboot POS app'],
        recommendedAction: 'Advise agent to re-try withdrawal transaction.',
      },
    ],
  },
  {
    id: 'PB-MERCHANT-SETTLEMENT',
    title: 'Merchant Payout & Batch Settlement Investigation',
    category: 'MERCHANT_SETTLEMENT',
    targetTier: 'TIER_2_SENIOR',
    estimatedMinutes: 5,
    requiredRole: 'TIER_2_SENIOR',
    applicableJurisdictions: ['NG', 'NE', 'CROSS_BORDER'],
    steps: [
      {
        stepNumber: 1,
        title: 'Verify Settlement Batch ID & Banking Rails',
        instructions: 'Locate the merchant batch reference in the settlement ledger. Check if Providus (NG) or Coris (NE) batch run is finalized.',
        checklistItems: ['Batch ID matched', 'Bank account details validated', 'No compliance hold active'],
        recommendedAction: 'Check Treasury balance on payout node.',
      },
      {
        stepNumber: 2,
        title: 'Confirm Dual-Authorization Release',
        instructions: 'High-value settlements (>₦10.0M or 10.0M XOF) require Treasury Maker-Checker sign-off.',
        checklistItems: ['Treasury release checked', 'Beneficiary bank status checked'],
        recommendedAction: 'Escalate to Finance Lead if batch is awaiting secondary checker.',
      },
    ],
  },
];

// ============================================================================
// 6. TRILINGUAL KNOWLEDGE BASE ARTICLES
// ============================================================================
export const MOCK_KNOWLEDGE_ARTICLES: KnowledgeArticle[] = [
  {
    id: 'KB-001',
    title: 'Understanding Pending NIP Bank Transfers & Auto-Reversal Windows',
    category: 'PENDING_TRANSACTION',
    audience: 'INTERNAL_OFFICER',
    language: 'en',
    problem: 'Customer complains their account was debited for an interbank transfer but the recipient has not received the credit.',
    symptoms: [
      'Transaction state shows PENDING on KoriePay ledger',
      'Beneficiary bank switch responded with timeout or error code 09',
      'Wallet balance debited immediately',
    ],
    resolution: '1. Reassure customer with the exact NIBSS 30-digit Session ID.\n2. Explain that the receiving bank has up to 1-2 hours for interbank settlement.\n3. If unfulfilled, KoriePay automated reconciliation engine automatically reverses the amount back to customer wallet.',
    escalationCondition: 'Transaction remains pending >24 hours with no reversal.',
    requiredPermissions: 'TIER_1_JUNIOR',
    version: '2.4',
    updatedAt: '2026-08-15',
    author: 'Haruna Dan-Borno',
    tags: ['NIP', 'Transfer', 'Providus', 'Reversal', 'NIBSS'],
    helpfulCount: 428,
  },
  {
    id: 'KB-002',
    title: 'Yadda Ake Magance Matsalar Canja Lambar Waya da Sabunta Asusu (Hausa)',
    category: 'LOGIN_ACCESS',
    audience: 'INTERNAL_OFFICER',
    language: 'ha',
    problem: 'Abokin ciniki yana son sauya lambar wayarsa saboda tsohuwar lambar ta bace ko ta lalace.',
    symptoms: [
      'Ba zai iya karbar lambar sirri ta OTP ba',
      'Yana buƙatar tabbatar da asalin kansa ta hanyar NIN',
    ],
    resolution: '1. Tabbatar da asalin abokin ciniki ta hanyar lambar NIN ko BVN.\n2. Bincika hoton fuskarsa (Biometric liveness selfie).\n3. Bayan an tabbatar da cikakken bayani, jami\'in Tier-2 zai amince da sauya lambar a cikin tsarin tsaro.',
    escalationCondition: 'Idan akwai alamar zamba ko kuma sunan NIN bai dace da na asusun ba.',
    requiredPermissions: 'TIER_1_JUNIOR',
    version: '1.8',
    updatedAt: '2026-08-20',
    author: 'Zainab Abubakar',
    tags: ['Hausa', 'Lambar Waya', 'NIN', 'Tsaro', 'OTP'],
    helpfulCount: 195,
  },
  {
    id: 'KB-003',
    title: 'Guide de Résolution des Rechargements Float et Terminaux POS au Niger (Français)',
    category: 'AGENT_FLOAT',
    audience: 'INTERNAL_OFFICER',
    language: 'fr',
    problem: 'L\'agent POS au Niger ne voit pas son solde float actualisé après un virement Coris Bank.',
    symptoms: [
      'Terminal affiche "Solde Insuffisant"',
      'Virement bancaire effectué depuis Coris Bank',
    ],
    resolution: '1. Vérifier la réception du virement sur le nœud Coris Bank NE.\n2. Cliquer sur "Synchroniser Float" dans la console d\'assistance.\n3. Demander à l\'agent de redémarrer l\'application sur le terminal PAX.',
    escalationCondition: 'Échec de synchronisation après 3 tentatives ou virement bancaire non trouvé.',
    requiredPermissions: 'TIER_1_JUNIOR',
    version: '2.1',
    updatedAt: '2026-08-25',
    author: 'Abdoul-Razak Souley',
    tags: ['Niger', 'Coris Bank', 'POS', 'Float', 'FCFA'],
    helpfulCount: 312,
  },
];

// ============================================================================
// 7. ACTIVE SYSTEM INCIDENTS
// ============================================================================
export const MOCK_SUPPORT_INCIDENTS: SupportIncident[] = [
  {
    id: 'INC-2026-0903-01',
    incidentNumber: 'INC-2026-0903-01',
    title: 'Transient NIP Outbound Transfer Latency on GTBank & Zenith Bank Switches',
    description: 'Interbank transfers destined for GTBank (058) and Zenith Bank (057) are experiencing elevated acknowledgment response times from NIBSS central switch.',
    affectedServices: ['NIP Bank Transfers', 'Quick Transfer Checkout'],
    affectedProviders: ['NIBSS', 'Providus Bank Core NG'],
    jurisdiction: 'NG',
    severity: 'MAJOR',
    status: 'IDENTIFIED',
    startTime: '2026-09-03T10:45:00Z',
    linkedTicketsCount: 14,
    customerNotice: 'We are aware that transfers to GTBank and Zenith Bank may take up to 30 minutes to reflect. Funds are safe and automated reversal is active.',
  },
];

// ============================================================================
// 8. AUTOMATION RULES & EXECUTION LOGS
// ============================================================================
export const MOCK_AUTOMATION_RULES: AutomationRule[] = [
  {
    id: 'RULE-001',
    ruleName: 'Auto-Acknowledge NIP Pending Transfers with NIBSS Trace ID',
    description: 'When a ticket is created regarding a pending transfer with age <60 minutes, automatically fetch the NIBSS session ID and send the approved reassurance macro.',
    triggerEvent: 'ticket.created',
    category: 'PENDING_TRANSACTION',
    conditions: [
      { field: 'category', operator: 'EQUALS', value: 'PENDING_TRANSACTION' },
      { field: 'transaction.ageMinutes', operator: 'LESS_THAN', value: '60' },
    ],
    actions: [
      { actionType: 'AUTO_RESPOND', parameters: { templateKey: 'MACRO_NIP_PENDING_ACK' } },
      { actionType: 'AUTO_ASSIGN', parameters: { tier: 'TIER_1_JUNIOR' } },
    ],
    enabled: true,
    executionCount: 1420,
    successRate: 98.6,
    lastTriggered: '2026-09-03T11:15:05Z',
    requiresHumanApproval: false,
    isDryRun: false,
  },
  {
    id: 'RULE-002',
    ruleName: 'Auto-Detect ATM Dispense Failures & Queue Reversal',
    description: 'When an ATM withdrawal returns RC91/RC96 from Interswitch, create an automated dispute ticket and queue for 24-hour reversal verification.',
    triggerEvent: 'transaction.failed',
    category: 'CARD',
    conditions: [
      { field: 'channel', operator: 'EQUALS', value: 'CARD_ATM' },
      { field: 'responseCode', operator: 'EQUALS', value: '91' },
    ],
    actions: [
      { actionType: 'AUTO_RESPOND', parameters: { templateKey: 'MACRO_ATM_REVERSAL_QUEUE' } },
    ],
    enabled: true,
    executionCount: 840,
    successRate: 99.2,
    lastTriggered: '2026-09-03T11:50:10Z',
    requiresHumanApproval: false,
    isDryRun: false,
  },
  {
    id: 'RULE-003',
    ruleName: 'Auto-Escalate Merchant Settlement Inquiries >₦10M to Finance',
    description: 'Automatically route high-value merchant payout inquiries to Senior Finance Operations officers.',
    triggerEvent: 'ticket.created',
    category: 'MERCHANT_SETTLEMENT',
    conditions: [
      { field: 'customerType', operator: 'EQUALS', value: 'MERCHANT' },
      { field: 'amount', operator: 'GREATER_THAN', value: '10000000' },
    ],
    actions: [
      { actionType: 'ESCALATE', parameters: { targetRole: 'TIER_3_FINANCE' } },
    ],
    enabled: true,
    executionCount: 310,
    successRate: 100.0,
    lastTriggered: '2026-09-03T09:00:00Z',
    requiresHumanApproval: true,
    isDryRun: false,
  },
];

export const MOCK_AUTOMATION_EXECUTION_LOGS: AutomationExecutionLog[] = [
  {
    id: 'LOG-AUTO-9910',
    ruleId: 'RULE-001',
    ruleName: 'Auto-Acknowledge NIP Pending Transfers with NIBSS Trace ID',
    ticketId: 'TCK-2026-10491',
    triggerTimestamp: '2026-09-03T11:15:05Z',
    status: 'SUCCESS',
    actionTaken: 'Fetched NIBSS Session ID and queued guided macro for Junior Officer Zainab.',
    timeSavedMinutes: 4.5,
  },
  {
    id: 'LOG-AUTO-9909',
    ruleId: 'RULE-002',
    ruleName: 'Auto-Detect ATM Dispense Failures & Queue Reversal',
    ticketId: 'TCK-2026-10495',
    triggerTimestamp: '2026-09-03T11:50:10Z',
    status: 'SUCCESS',
    actionTaken: 'Classified ATM RC91 dispense error. Auto-created dispute workflow.',
    timeSavedMinutes: 6.0,
  },
];

// ============================================================================
// 9. QUALITY ASSURANCE (QA) REVIEWS
// ============================================================================
export const MOCK_QA_REVIEWS: QaReview[] = [
  {
    id: 'QA-2026-0041',
    ticketId: 'TCK-2026-10488',
    officerId: 'OFF-SUP-01',
    officerName: 'Zainab Abubakar',
    reviewerName: 'Haruna Dan-Borno (Supervisor)',
    score: 96,
    criteriaRatings: {
      identityVerification: 100,
      accuracy: 95,
      professionalism: 98,
      playbookAdherence: 95,
      resolutionSpeed: 92,
    },
    feedback: 'Excellent use of Hausa response macro. Provided the exact NIBSS session reference to customer. Resolved well within SLA.',
    reviewedAt: '2026-09-02T16:45:00Z',
  },
];

// ============================================================================
// 10. JUNIOR STAFF TRAINING & CERTIFICATION ACADEMY
// ============================================================================
export const MOCK_TRAINING_MODULES: TrainingModule[] = [
  {
    id: 'MOD-01',
    title: 'Fintech Fundamentals & KoriePay Dual-Node Architecture',
    description: 'Understanding how Providus Bank (Nigeria) and Coris Bank (Niger) process real-time transactions and virtual NUBANs.',
    tier: 'TIER_1_JUNIOR',
    estimatedMinutes: 25,
    modulesCount: 5,
    completed: true,
    score: 100,
    certificationName: 'KoriePay Certified Junior Operator (Level 1)',
    keySkills: ['Providus Virtual NUBANs', 'Coris XOF Clearing', 'Ledger Basics'],
  },
  {
    id: 'MOD-02',
    title: 'Handling NIP & Mobile Money Failed/Pending Transactions',
    description: 'Mastering the 4-step NIP investigation playbook, identifying error codes, and communicating reassurance to customers.',
    tier: 'TIER_1_JUNIOR',
    estimatedMinutes: 30,
    modulesCount: 6,
    completed: true,
    score: 95,
    certificationName: 'Transaction Resolution Specialist',
    keySkills: ['NIBSS Session Tracing', 'Auto-Reversals', 'Playbook Execution'],
  },
  {
    id: 'MOD-03',
    title: 'Fraud Prevention, Social Engineering & Account Takeover Defense',
    description: 'Recognizing impersonation, phishing, SIM-swap indicators, and escalating security threats safely without disclosing data.',
    tier: 'TIER_1_JUNIOR',
    estimatedMinutes: 40,
    modulesCount: 8,
    completed: false,
    certificationName: 'Frontline Security Defender',
    keySkills: ['Social Engineering Detection', 'Data Minimization', 'Emergency Freezing'],
  },
];

// ============================================================================
// 11. STAFF CAPACITY & WORKFORCE ANALYTICS
// ============================================================================
export const MOCK_STAFF_CAPACITY: StaffCapacityMetric = {
  currentWorkforce: 24,
  peakQueueRequirement: 31,
  recommendedJuniorOfficers: 7,
  primaryNeedCategory: 'Transfer & Account Support (Hausa & French)',
  languageDemand: {
    english: 58,
    hausa: 28,
    french: 14,
  },
};

// ============================================================================
// 12. OVERALL SUPPORT HEALTH SCORE
// ============================================================================
export const MOCK_SUPPORT_HEALTH_SCORE: SupportHealthScore = {
  overallScore: 92.4,
  responsePerformance: 94.0,
  resolutionPerformance: 91.5,
  slaCompliance: 96.8,
  csat: 94.2,
  automationEfficiency: 88.5,
  backlogHealth: 90.0,
  staffCapacity: 86.0,
};

// ============================================================================
// 13. IMMUTABLE SUPPORT AUDIT LOGS
// ============================================================================
export const MOCK_SUPPORT_AUDIT_LOGS: SupportAuditEntry[] = [
  {
    id: 'AUD-SUP-2026-901',
    timestamp: '2026-09-03T11:45:00Z',
    officerId: 'OFF-SUP-01',
    officerName: 'Zainab Abubakar',
    officerRole: 'TIER_1_JUNIOR',
    action: 'TICKET_MESSAGE_SENT',
    entityType: 'SUPPORT_TICKET',
    entityId: 'TCK-2026-10491',
    details: 'Sent approved NIP reassurance macro to customer Ibrahim Danladi referencing NIBSS Session ID 99920126090311100012.',
    jurisdiction: 'NG',
  },
  {
    id: 'AUD-SUP-2026-900',
    timestamp: '2026-09-03T10:38:00Z',
    officerId: 'OFF-SUP-02',
    officerName: 'Abdoul-Razak Souley',
    officerRole: 'TIER_1_JUNIOR',
    action: 'AGENT_FLOAT_SYNCED',
    entityType: 'AGENT_TERMINAL',
    entityId: 'AGT-NE-2009',
    details: 'Triggered MQTT cloud float refresh to PAX Terminal #02 at Niamey Grand Marché.',
    jurisdiction: 'NE',
  },
  {
    id: 'AUD-SUP-2026-899',
    timestamp: '2026-09-03T09:20:00Z',
    officerId: 'OFF-SUP-03',
    officerName: 'Chidinma Eze',
    officerRole: 'TIER_2_SENIOR',
    action: 'TICKET_ESCALATED_FINANCE',
    entityType: 'SUPPORT_TICKET',
    entityId: 'TCK-2026-10493',
    details: 'Escalated merchant settlement inquiry of ₦14.2M to Finance Operations for Treasury batch clearance.',
    jurisdiction: 'CROSS_BORDER',
  },
];
