import { NextRequest } from 'next/server';
import { authenticateAggregatorRequest } from '@/lib/security/aggregatorAuth';
import { getSupabaseAdminClient } from '@/lib/supabase/admin';
import { createSuccessResponse, createErrorResponse } from '@/lib/security/apiResponse';

/**
 * GET /api/v1/aggregator/audit — real public.aggregator_audit_logs rows
 * generated by every mutating action across the aggregator API surface.
 */
export async function GET(req: NextRequest) {
  const auth = await authenticateAggregatorRequest(req, { requireActiveStatus: false });
  if (!auth.isAuthenticated || !auth.staff) {
    return createErrorResponse({ code: auth.errorCode || 'UNAUTHORIZED', message: auth.errorMessage || 'Unauthorized', requestId: `KP-REQ-${Date.now()}`, httpStatus: auth.httpStatus || 401 });
  }
  const { staff } = auth;
  const admin = getSupabaseAdminClient();

  const limit = Math.min(Number(req.nextUrl.searchParams.get('limit')) || 100, 300);

  const { data, error } = await admin
    .from('aggregator_audit_logs')
    .select('id, action, target_type, target_id, result, reason, created_at, aggregator_staff_users(full_name, role)')
    .eq('aggregator_id', staff.aggregatorId)
    .order('created_at', { ascending: false })
    .limit(limit);

  if (error) {
    return createErrorResponse({ code: 'AUDIT_LOOKUP_FAILED', message: 'Could not load audit log.', requestId: staff.requestId, httpStatus: 500 });
  }

  const mapped = (data || []).map((a: any) => ({
    id: a.id,
    action: a.action,
    targetType: a.target_type,
    targetId: a.target_id,
    result: a.result,
    reason: a.reason,
    actorName: a.aggregator_staff_users?.full_name || 'System',
    actorRole: a.aggregator_staff_users?.role || '—',
    createdAt: a.created_at,
  }));

  return createSuccessResponse({ auditLog: mapped }, { code: 'AUDIT_RETRIEVED', requestId: staff.requestId, environment: 'PRODUCTION' });
}
