"use client";

import React, { useMemo, useState } from "react";
import { useAggregator } from "@/components/aggregator/AggregatorContext";
import { Bell, CheckCheck, Inbox } from "lucide-react";

const CATEGORY_TONE: Record<string, string> = {
  FINANCIAL: "text-emerald-600 dark:text-emerald-400 bg-emerald-500/10 border-emerald-500/30",
  OPERATIONS: "text-amber-600 dark:text-amber-400 bg-amber-500/10 border-amber-500/30",
  COMPLIANCE: "text-sky-600 dark:text-sky-400 bg-sky-500/10 border-sky-500/30",
  SECURITY: "text-rose-600 dark:text-rose-400 bg-rose-500/10 border-rose-500/30",
};

export default function AggregatorNotificationsPage() {
  const { notifications, markNotificationRead, markAllNotificationsRead, formatDate, t, notificationsCount } = useAggregator();
  const [filter, setFilter] = useState<"ALL" | "UNREAD">("ALL");

  const shown = useMemo(() => {
    const sorted = [...notifications].sort((a, b) => new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime());
    return filter === "UNREAD" ? sorted.filter((n) => !n.isRead) : sorted;
  }, [notifications, filter]);

  const unread = notifications.filter((n) => !n.isRead).length;

  return (
    <div className="p-4 sm:p-6 lg:p-8 space-y-6 max-w-5xl mx-auto">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3">
        <div>
          <h1 className="text-xl sm:text-2xl font-black text-[var(--foreground)]">Aggregator Notification Center</h1>
          <p className="text-xs text-[var(--foreground-muted)]">
            Operational notifications generated by real events — settlements, float thresholds, compliance and security.
          </p>
        </div>
        <div className="flex items-center gap-2">
          <div className="flex items-center gap-1 p-1 rounded-2xl bg-[var(--surface-2)] border border-[var(--border)] text-xs font-mono">
            {(["ALL", "UNREAD"] as const).map((f) => (
              <button
                key={f}
                onClick={() => setFilter(f)}
                className={`px-3 py-1 rounded-xl font-bold ${filter === f ? "bg-teal-500 text-slate-950" : "text-[var(--foreground-muted)] hover:text-[var(--foreground)]"}`}
              >
                {f === "ALL" ? notifications.length : `${unread}`}
              </button>
            ))}
          </div>
          {unread > 0 && (
            <button
              onClick={() => void markAllNotificationsRead()}
              className="flex items-center gap-1.5 px-3 py-2 rounded-xl text-xs font-bold border border-[var(--border)] text-[var(--foreground-muted)] hover:text-[var(--foreground)]"
            >
              <CheckCheck className="w-3.5 h-3.5" />
              Mark all read
            </button>
          )}
        </div>
      </div>

      {/* List */}
      {shown.length === 0 ? (
        <div className="p-10 rounded-3xl bg-[var(--surface)] border border-[var(--border)] text-center">
          <Inbox className="w-8 h-8 mx-auto text-[var(--foreground-muted)] mb-3" />
          <div className="text-sm font-bold text-[var(--foreground)]">
            {filter === "UNREAD" ? "No unread notifications" : "No notifications yet"}
          </div>
          <p className="text-xs text-[var(--foreground-muted)] mt-1 max-w-md mx-auto">
            Notifications appear here when the network generates them — float threshold breaches, settlement batches,
            compliance decisions and security events.
          </p>
        </div>
      ) : (
        <div className="space-y-3">
          {shown.map((n) => (
            <div
              key={n.id}
              className={`p-4 sm:p-5 rounded-2xl border transition-all flex items-start gap-4 ${
                !n.isRead ? "bg-[var(--surface-2)] border-amber-500/30" : "bg-[var(--surface)] border-[var(--border)] opacity-80"
              }`}
            >
              <div className="w-9 h-9 rounded-xl bg-[var(--surface-2)] border border-[var(--border)] flex items-center justify-center shrink-0 text-amber-600 dark:text-amber-400">
                <Bell className="w-4 h-4" />
              </div>

              <div className="space-y-1 flex-1 min-w-0">
                <div className="flex flex-wrap items-center justify-between gap-2">
                  <span className="font-bold text-sm text-[var(--foreground)]">{n.title}</span>
                  <span className="text-[10px] font-mono text-[var(--foreground-muted)] shrink-0">{formatDate(n.createdAt)}</span>
                </div>
                <p className="text-xs text-[var(--foreground-muted)]">{n.body}</p>
                <div className="flex items-center gap-2 pt-1">
                  <span
                    className={`px-2 py-0.5 rounded-full text-[9px] font-mono font-bold border ${
                      CATEGORY_TONE[n.category?.toUpperCase()] || "text-[var(--foreground-muted)] bg-[var(--surface)] border-[var(--border)]"
                    }`}
                  >
                    {n.category || "GENERAL"}
                  </span>
                  <span
                    className={`px-2 py-0.5 rounded-full text-[9px] font-mono font-bold border ${
                      n.severity === "CRITICAL" || n.severity === "HIGH"
                        ? "text-rose-600 dark:text-rose-400 bg-rose-500/10 border-rose-500/30"
                        : "text-[var(--foreground-muted)] bg-[var(--surface)] border-[var(--border)]"
                    }`}
                  >
                    {n.severity || "INFO"}
                  </span>
                  {!n.isRead && (
                    <button
                      onClick={() => void markNotificationRead(n.id)}
                      className="ml-auto text-[10px] font-bold text-teal-600 dark:text-teal-400 hover:underline"
                    >
                      Mark read
                    </button>
                  )}
                </div>
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}
