import { ChartOfAccountItem } from '@/types/financialEngine';

export const CHART_OF_ACCOUNTS: Record<string, ChartOfAccountItem> = {
  // 1xxx: ASSETS
  '1010': {
    code: '1010',
    name: 'Providus Settlement Pool NGN',
    category: 'ASSET',
    normalBalance: 'DEBIT',
    description: 'Bank settlement operating account at Providus Bank Nigeria',
    currency: 'NGN',
    country: 'NG',
    isActive: true,
  },
  '1020': {
    code: '1020',
    name: 'Coris Bank Settlement Pool XOF',
    category: 'ASSET',
    normalBalance: 'DEBIT',
    description: 'Bank settlement operating account at Coris Bank Niger Republic',
    currency: 'XOF',
    country: 'NE',
    isActive: true,
  },
  '1030': {
    code: '1030',
    name: 'Central Reserve USD Nostro',
    category: 'ASSET',
    normalBalance: 'DEBIT',
    description: 'FX Nostro clearing balance in USD',
    currency: 'USD',
    country: 'CROSS_BORDER',
    isActive: true,
  },
  '1110': {
    code: '1110',
    name: 'Customer Transit Clearing NGN',
    category: 'ASSET',
    normalBalance: 'DEBIT',
    description: 'In-flight NIP collections and card transit receivables',
    currency: 'NGN',
    country: 'NG',
    isActive: true,
  },
  '1120': {
    code: '1120',
    name: 'Agent Float Clearing XOF',
    category: 'ASSET',
    normalBalance: 'DEBIT',
    description: 'In-flight agency cash-in transit receivables',
    currency: 'XOF',
    country: 'NE',
    isActive: true,
  },
  '1210': {
    code: '1210',
    name: 'Provider Receivables (Aggregators)',
    category: 'ASSET',
    normalBalance: 'DEBIT',
    description: 'Receivables from aggregator card & virtual collections',
    currency: 'NGN',
    country: 'NG',
    isActive: true,
  },
  '1040': {
    code: '1040',
    name: 'Physical Cash in Branch Vaults NGN',
    category: 'ASSET',
    normalBalance: 'DEBIT',
    description: 'Physical currency held in central, regional, and branch vaults in Nigeria',
    currency: 'NGN',
    country: 'NG',
    isActive: true,
  },
  '1050': {
    code: '1050',
    name: 'Physical Cash in Branch Vaults XOF',
    category: 'ASSET',
    normalBalance: 'DEBIT',
    description: 'Physical currency held in vaults in Niger Republic',
    currency: 'XOF',
    country: 'NE',
    isActive: true,
  },
  '1060': {
    code: '1060',
    name: 'Cash-in-Transit (CIT) in Custody NGN',
    category: 'ASSET',
    normalBalance: 'DEBIT',
    description: 'Physical currency currently under CIT courier custody in Nigeria',
    currency: 'NGN',
    country: 'NG',
    isActive: true,
  },
  '1070': {
    code: '1070',
    name: 'Cash-in-Transit (CIT) in Custody XOF',
    category: 'ASSET',
    normalBalance: 'DEBIT',
    description: 'Physical currency currently under CIT courier custody in Niger Republic',
    currency: 'XOF',
    country: 'NE',
    isActive: true,
  },
  '1080': {
    code: '1080',
    name: 'Agent Physical Cash-in-Custody NGN',
    category: 'ASSET',
    normalBalance: 'DEBIT',
    description: 'Physical currency held across agent network tills in Nigeria',
    currency: 'NGN',
    country: 'NG',
    isActive: true,
  },
  '1090': {
    code: '1090',
    name: 'Agent Physical Cash-in-Custody XOF',
    category: 'ASSET',
    normalBalance: 'DEBIT',
    description: 'Physical currency held across agent network tills in Niger Republic',
    currency: 'XOF',
    country: 'NE',
    isActive: true,
  },

  // 2xxx: LIABILITIES
  '2010': {
    code: '2010',
    name: 'Customer Wallet Deposits NGN',
    category: 'LIABILITY',
    normalBalance: 'CREDIT',
    description: 'Customer wallet balances payable on demand in NGN',
    currency: 'NGN',
    country: 'NG',
    isActive: true,
  },
  '2020': {
    code: '2020',
    name: 'Customer Wallet Deposits XOF',
    category: 'LIABILITY',
    normalBalance: 'CREDIT',
    description: 'Customer wallet balances payable on demand in XOF',
    currency: 'XOF',
    country: 'NE',
    isActive: true,
  },
  '2030': {
    code: '2030',
    name: 'Agent Operational Float NGN',
    category: 'LIABILITY',
    normalBalance: 'CREDIT',
    description: 'Agent wallet working capital liability NGN',
    currency: 'NGN',
    country: 'NG',
    isActive: true,
  },
  '2040': {
    code: '2040',
    name: 'Agent Operational Float XOF',
    category: 'LIABILITY',
    normalBalance: 'CREDIT',
    description: 'Agent wallet working capital liability XOF',
    currency: 'XOF',
    country: 'NE',
    isActive: true,
  },
  '2050': {
    code: '2050',
    name: 'Merchant Payables NGN',
    category: 'LIABILITY',
    normalBalance: 'CREDIT',
    description: 'Undispatched merchant checkout settlements in NGN',
    currency: 'NGN',
    country: 'NG',
    isActive: true,
  },
  '2060': {
    code: '2060',
    name: 'Merchant Payables XOF',
    category: 'LIABILITY',
    normalBalance: 'CREDIT',
    description: 'Undispatched merchant checkout settlements in XOF',
    currency: 'XOF',
    country: 'NE',
    isActive: true,
  },
  '2100': {
    code: '2100',
    name: 'Dispute & Chargeback Reserves',
    category: 'LIABILITY',
    normalBalance: 'CREDIT',
    description: 'Held reserves for contested customer transactions',
    currency: 'NGN',
    country: 'NG',
    isActive: true,
  },

  // 3xxx: EQUITY
  '3010': {
    code: '3010',
    name: 'Retained Platform Earnings',
    category: 'EQUITY',
    normalBalance: 'CREDIT',
    description: 'Cumulative platform retained net profit',
    currency: 'NGN',
    country: 'CROSS_BORDER',
    isActive: true,
  },
  '3020': {
    code: '3020',
    name: 'FX Realized Translation Reserve',
    category: 'EQUITY',
    normalBalance: 'CREDIT',
    description: 'Cumulative realized gain/loss from currency spreads',
    currency: 'NGN',
    country: 'CROSS_BORDER',
    isActive: true,
  },

  // 4xxx: REVENUE
  '4010': {
    code: '4010',
    name: 'Transfer Processing Fee Income NGN',
    category: 'REVENUE',
    normalBalance: 'CREDIT',
    description: 'Fee revenue earned on customer P2P/NIP transfers',
    currency: 'NGN',
    country: 'NG',
    isActive: true,
  },
  '4020': {
    code: '4020',
    name: 'Transfer Processing Fee Income XOF',
    category: 'REVENUE',
    normalBalance: 'CREDIT',
    description: 'Fee revenue earned on customer transfers in Niger',
    currency: 'XOF',
    country: 'NE',
    isActive: true,
  },
  '4030': {
    code: '4030',
    name: 'Merchant MDR Checkout Fee Income',
    category: 'REVENUE',
    normalBalance: 'CREDIT',
    description: 'Merchant discount rate revenue from card & QR checkout',
    currency: 'NGN',
    country: 'NG',
    isActive: true,
  },
  '4040': {
    code: '4040',
    name: 'FX Cross-Border Spread Revenue',
    category: 'REVENUE',
    normalBalance: 'CREDIT',
    description: 'Spread earned on NGN/XOF currency conversion',
    currency: 'NGN',
    country: 'CROSS_BORDER',
    isActive: true,
  },
  '4050': {
    code: '4050',
    name: 'Agency Cash-in/Cash-out Commission Revenue',
    category: 'REVENUE',
    normalBalance: 'CREDIT',
    description: 'Platform fee take from agent transactions',
    currency: 'NGN',
    country: 'NG',
    isActive: true,
  },

  // 5xxx: EXPENSES
  '5010': {
    code: '5010',
    name: 'Providus NIP Rail Interchange Expense',
    category: 'EXPENSE',
    normalBalance: 'DEBIT',
    description: 'NIP switch interchange fee paid to bank',
    currency: 'NGN',
    country: 'NG',
    isActive: true,
  },
  '5020': {
    code: '5020',
    name: 'Coris Bank Rail Processing Expense',
    category: 'EXPENSE',
    normalBalance: 'DEBIT',
    description: 'Interbank rail processing cost in Niger',
    currency: 'XOF',
    country: 'NE',
    isActive: true,
  },
  '5030': {
    code: '5030',
    name: 'Agent Distribution Commission Expense',
    category: 'EXPENSE',
    normalBalance: 'DEBIT',
    description: 'Commission paid out to agent network',
    currency: 'NGN',
    country: 'NG',
    isActive: true,
  },
  '5040': {
    code: '5040',
    name: 'Aggregator Gateway Processing Expense',
    category: 'EXPENSE',
    normalBalance: 'DEBIT',
    description: 'Interchange and processing fees paid to card aggregators',
    currency: 'NGN',
    country: 'NG',
    isActive: true,
  },

  // 6xxx: CONTROL & CLEARING
  '6010': {
    code: '6010',
    name: 'Cross-Border FX Bridge Clearing (NGN/XOF)',
    category: 'CONTROL',
    normalBalance: 'DEBIT',
    description: 'Zero-sum clearing account for cross-border atomic transfers',
    currency: 'MULTI',
    country: 'CROSS_BORDER',
    isActive: true,
  },
  '6020': {
    code: '6020',
    name: 'Merchant Batch Settlement In-Flight',
    category: 'CLEARING',
    normalBalance: 'DEBIT',
    description: 'Interim clearing for NIP payout batches',
    currency: 'NGN',
    country: 'NG',
    isActive: true,
  },

  // 7xxx: SUSPENSE
  '7100': {
    code: '7100',
    name: 'Unallocated Inbound NIP Deposits Suspense',
    category: 'SUSPENSE',
    normalBalance: 'CREDIT',
    description: 'Inbound bank transfers without matching virtual account',
    currency: 'NGN',
    country: 'NG',
    isActive: true,
  },
  '7200': {
    code: '7200',
    name: 'Failed Outbound Settlement Suspense',
    category: 'SUSPENSE',
    normalBalance: 'DEBIT',
    description: 'Debited payout funds where bank status is unverified or timed out',
    currency: 'NGN',
    country: 'NG',
    isActive: true,
  },
  '7300': {
    code: '7300',
    name: 'Reconciliation Discrepancy Suspense',
    category: 'SUSPENSE',
    normalBalance: 'DEBIT',
    description: 'Audit discrepancies under manual maker-checker investigation',
    currency: 'NGN',
    country: 'CROSS_BORDER',
    isActive: true,
  },
  '7400': {
    code: '7400',
    name: 'Physical Cash Variance Suspense',
    category: 'SUSPENSE',
    normalBalance: 'DEBIT',
    description: 'Physical cash till and vault shortages/overages awaiting maker-checker resolution',
    currency: 'MULTI',
    country: 'CROSS_BORDER',
    isActive: true,
  },
};

export function getAccountByCode(code: string): ChartOfAccountItem | undefined {
  return CHART_OF_ACCOUNTS[code];
}

export function getAllAccounts(): ChartOfAccountItem[] {
  return Object.values(CHART_OF_ACCOUNTS);
}

export function getAccountsByCategory(category: string): ChartOfAccountItem[] {
  return Object.values(CHART_OF_ACCOUNTS).filter(acc => acc.category === category);
}
