"use client";

import React, { useState } from "react";
import { PageHeader, fmtDate } from "@/components/admin/AdminPageUI";
import ResourceTable, { StatusChip, ResourceColumn } from "@/components/admin/ResourceTable";
import { useAdmin } from "@/components/admin/AdminContext";

/**
 * Intelligence — live management KPIs, decision recommendations, board
 * reports and financial forecasts. The old page rendered an in-memory
 * decision engine; recommendations and KPIs are now whatever the
 * analytics pipeline actually produced.
 */
export default function IntelligencePage() {
  const { openDrawer } = useAdmin();
  const [tab, setTab] = useState<"kpis" | "decisions" | "board" | "forecasts">("kpis");

  const kpiCols: ResourceColumn[] = [
    { key: "kpi_code", label: "KPI", render: (r) => <span className="font-bold text-[var(--foreground)]">{r.kpi_code}</span> },
    { key: "name", label: "Name" },
    { key: "domain", label: "Domain", render: (r) => <span className="px-2 py-0.5 rounded text-[10px] font-bold uppercase bg-[var(--brand-soft)] text-[var(--brand-primary)] border border-[var(--brand-primary)]/20">{String(r.domain ?? "—").replaceAll("_", " ")}</span> },
    { key: "target_value", label: "Target", className: "text-right" },
    { key: "actual_value", label: "Actual", className: "text-right", render: (r) => <span className="font-bold">{r.actual_value ?? "—"}</span> },
    { key: "variance_pct", label: "Variance", className: "text-right", render: (r) => <span className={Number(r.variance_pct) > 0 ? "text-emerald-400" : "text-rose-400"}>{r.variance_pct ?? "—"}%</span> },
    { key: "status", label: "Status", render: (r) => <StatusChip value={r.status} /> },
    { key: "updated_at", label: "Updated", hideOnMobile: true, render: (r) => <span className="text-[var(--foreground-muted)]">{fmtDate(r.updated_at)}</span> },
  ];

  const decisionCols: ResourceColumn[] = [
    { key: "created_at", label: "Raised", render: (r) => <span className="text-[var(--foreground-muted)]">{fmtDate(r.created_at)}</span> },
    { key: "decision_code", label: "Decision", render: (r) => <span className="font-bold text-[var(--foreground)]">{r.decision_code}</span> },
    { key: "title", label: "Recommendation" },
    { key: "materiality_tier", label: "Tier", hideOnMobile: true },
    { key: "confidence_pct", label: "Confidence", className: "text-right", render: (r) => <span>{r.confidence_pct != null ? `${r.confidence_pct}%` : "—"}</span> },
    { key: "status", label: "Status", render: (r) => <StatusChip value={r.status} /> },
  ];

  const boardCols: ResourceColumn[] = [
    { key: "created_at", label: "Created", render: (r) => <span className="text-[var(--foreground-muted)]">{fmtDate(r.created_at)}</span> },
    { key: "report_code", label: "Report", render: (r) => <span className="font-bold text-[var(--foreground)]">{r.report_code}</span> },
    { key: "meeting_period", label: "Period" },
    { key: "generated_by", label: "Generated by", hideOnMobile: true },
    { key: "published_at", label: "Published", hideOnMobile: true, render: (r) => <span className="text-[var(--foreground-muted)]">{r.published_at ? fmtDate(r.published_at) : "—"}</span> },
    { key: "status", label: "Status", render: (r) => <StatusChip value={r.status} /> },
  ];

  const forecastCols: ResourceColumn[] = [
    { key: "created_at", label: "Created", render: (r) => <span className="text-[var(--foreground-muted)]">{fmtDate(r.created_at)}</span> },
    { key: "forecast_code", label: "Forecast", render: (r) => <span className="font-bold text-[var(--foreground)]">{r.forecast_code}</span> },
    { key: "revenue_projected", label: "Revenue", className: "text-right" },
    { key: "net_profit_projected", label: "Net profit", className: "text-right" },
    { key: "ending_treasury_cash", label: "Ending cash", className: "text-right" },
    { key: "created_by", label: "By", hideOnMobile: true },
    { key: "status", label: "Status", render: (r) => <StatusChip value={r.status} /> },
  ];

  const tabs = [
    ["kpis", "Management KPIs"],
    ["decisions", "Decisions"],
    ["board", "Board reports"],
    ["forecasts", "Forecasts"],
  ] as const;

  return (
    <div className="p-4 sm:p-6 lg:p-8 space-y-6 max-w-7xl mx-auto">
      <PageHeader
        eyebrow="Intelligence"
        title="Management Intelligence"
        subtitle="KPI scorecards, decision recommendations, board packs and financial forecasts produced by the analytics pipeline — with audited decision outcomes."
      />

      <div className="flex flex-wrap gap-2 text-xs font-bold">
        {tabs.map(([t, label]) => (
          <button
            key={t}
            onClick={() => setTab(t)}
            className={`px-4 py-2 rounded-xl border transition-colors ${tab === t ? "bg-[var(--brand-primary)] text-white border-[var(--brand-primary)]" : "bg-[var(--surface)] text-[var(--foreground-muted)] border-[var(--border)] hover:border-[var(--brand-primary)]"}`}
          >
            {label}
          </button>
        ))}
      </div>

      {tab === "kpis" && (
        <ResourceTable resource="management-kpis" columns={kpiCols} exportName="management-kpis" searchPlaceholder="Search KPI code, name…" filters={[{ key: "domain", label: "Domain" }, { key: "status", label: "Status" }]} />
      )}
      {tab === "decisions" && (
        <ResourceTable resource="decision-recommendations" columns={decisionCols} exportName="decisions" searchPlaceholder="Search decision code, title…" filters={[{ key: "status", label: "Status" }]} onRowClick={(row) => openDrawer("DECISION", row)} />
      )}
      {tab === "board" && (
        <ResourceTable resource="board-reports" columns={boardCols} exportName="board-reports" searchPlaceholder="Search report code…" filters={[{ key: "status", label: "Status" }]} />
      )}
      {tab === "forecasts" && (
        <ResourceTable resource="financial-forecasts" columns={forecastCols} exportName="forecasts" filters={[{ key: "status", label: "Status" }]} />
      )}
    </div>
  );
}
